/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.siseduc.view;

import java.awt.Color;
import java.awt.Frame;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.ImageIcon;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author Juan Soares
 */
public class Mensagem extends javax.swing.JDialog {

    public static final int MSG_INFORMATION = 1;
    public static final int MSG_QUESTION = 2;
    public static final int MSG_ERROR = 3;
    
    public static final int OPCAO_OK = 1;
    public static final int OPCAO_CANCELAR = 2;
    
    private int opcao;
    
    /**
     * Creates new form Mensagem
     * @param parent
     * @param modal
     */
    public Mensagem(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();        
        
        String okName = "Ok";
        InputMap inputMap = this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), okName);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), okName);
        ActionMap actionMap = this.getRootPane().getActionMap();
        actionMap.put(okName, new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                setOpcao(OPCAO_OK);
                setVisible(false);
                dispose();
            }
        });
    }

    /**
     * 
     * @param titulo
     * @param msg 
     * @param tipo 
     * @return  
     */
    public int showMessage(String titulo, String msg, int tipo) {
        this.setTitle(titulo);
        this.txtMessenger.setText(msg);
        
        switch (tipo) {
            case MSG_INFORMATION :
                laOk.setText("Ok");
                laCancelar.setVisible(false);
                break;
            case MSG_QUESTION :
                laOk.setText("Sim");
                laCancelar.setVisible(true);
                break;
            case MSG_ERROR:
                laOk.setText("Ok");
                laCancelar.setVisible(false);
                Toolkit.getDefaultToolkit().beep();
                break;
            default :
                return -1;
        }       
                
        this.pack();
        this.laCancelar.setForeground(Color.BLACK);
        this.laOk.setForeground(Color.BLACK);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        
        return getOpcao();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        laCancelar = new javax.swing.JLabel();
        laOk = new javax.swing.JLabel();
        txtMessenger = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setIconImage(new ImageIcon(getClass().getResource("/images/icone.png")).getImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });

        laCancelar.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        laCancelar.setText("Cancelar");
        laCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        laCancelar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                laCancelarMouseMoved(evt);
            }
        });
        laCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laCancelarMouseClicked(evt);
            }
        });

        laOk.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        laOk.setText("Ok");
        laOk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        laOk.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                laOkMouseMoved(evt);
            }
        });
        laOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laOkMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(laOk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(laCancelar)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laCancelar)
                    .addComponent(laOk))
                .addContainerGap())
        );

        txtMessenger.setEditable(false);
        txtMessenger.setBorder(null);
        txtMessenger.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtMessenger.setFocusable(false);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/msg.png"))); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMessenger, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMessenger))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void laCancelarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laCancelarMouseMoved
        laCancelar.setForeground(new Color(0,193,211));
    }//GEN-LAST:event_laCancelarMouseMoved

    private void laOkMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laOkMouseMoved
        laOk.setForeground(new Color(0,193,211));
    }//GEN-LAST:event_laOkMouseMoved

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
        laCancelar.setForeground(Color.BLACK);
        laOk.setForeground(Color.BLACK);
    }//GEN-LAST:event_jPanel1MouseMoved

    private void laOkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laOkMouseClicked
        this.txtMessenger.setText(null);
        this.dispose();
        this.setVisible(false);
        
        this.setOpcao(OPCAO_OK);
    }//GEN-LAST:event_laOkMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.setOpcao(OPCAO_CANCELAR);        
    }//GEN-LAST:event_formWindowClosing

    private void laCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laCancelarMouseClicked
        this.setOpcao(OPCAO_CANCELAR);
        
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_laCancelarMouseClicked

    public int getOpcao() {
        return opcao;
    }

    public void setOpcao(int opcao) {
        this.opcao = opcao;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel laCancelar;
    private javax.swing.JLabel laOk;
    private javax.swing.JTextPane txtMessenger;
    // End of variables declaration//GEN-END:variables
}
