/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.siseduc.view;

import javax.swing.JCheckBox;
import javax.swing.JDialog;
import javax.swing.JPasswordField;
import javax.swing.JRadioButton;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;

/**
 *
 * @author Juan Soares
 */
public class TelaCadastroUsuario extends javax.swing.JPanel {

    /**
     *
     */
    private static final long serialVersionUID = 6223711635492482942L;

    /**
     *
     */
    private final JTabbedPane jTabbedPane;

    /**
     *
     */
    private final JDialog jDialog;

    /**
     * Creates new form TelaCadastroUsuario
     *
     * @param jTabbedPane painel
     * @param jDialog janela
     */
    public TelaCadastroUsuario(JTabbedPane jTabbedPane, JDialog jDialog) {
        initComponents();
        this.jTabbedPane = jTabbedPane;
        this.jDialog = jDialog;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        buttonGroup11 = new javax.swing.ButtonGroup();
        buttonGroup12 = new javax.swing.ButtonGroup();
        buttonGroup13 = new javax.swing.ButtonGroup();
        buttonGroup14 = new javax.swing.ButtonGroup();
        buttonGroup15 = new javax.swing.ButtonGroup();
        buttonGroup16 = new javax.swing.ButtonGroup();
        buttonGroup17 = new javax.swing.ButtonGroup();
        buttonGroup18 = new javax.swing.ButtonGroup();
        buttonGroup19 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txtLogin = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        txtRepetirSenha = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        checkUsuarioMaster = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        rbCAAlunoSim = new javax.swing.JRadioButton();
        rbCAAlunoNao = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        rbCAProfessorSim = new javax.swing.JRadioButton();
        rbCAProfessorNao = new javax.swing.JRadioButton();
        jPanel8 = new javax.swing.JPanel();
        rbCAFuncionarioSim = new javax.swing.JRadioButton();
        rbCAFuncionarioNao = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        rbControleFinanceiroSim = new javax.swing.JRadioButton();
        rbControleFinanceiroNao = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        rbExcluirAlunoSim = new javax.swing.JRadioButton();
        rbExcluirAlunoNao = new javax.swing.JRadioButton();
        jPanel9 = new javax.swing.JPanel();
        rbCadastrarUsuarioSim = new javax.swing.JRadioButton();
        rbCadastrarUsuarioNao = new javax.swing.JRadioButton();
        jPanel10 = new javax.swing.JPanel();
        rbExcluirProfessorSim = new javax.swing.JRadioButton();
        rbExcluirProfessorNao = new javax.swing.JRadioButton();
        jPanel11 = new javax.swing.JPanel();
        rbExcluirFuncionarioSim = new javax.swing.JRadioButton();
        rbExcluirFuncionarioNao = new javax.swing.JRadioButton();
        jPanel15 = new javax.swing.JPanel();
        rbEmitirRelatoriosSim = new javax.swing.JRadioButton();
        rbEmitirRelatoriosNao = new javax.swing.JRadioButton();
        jPanel16 = new javax.swing.JPanel();
        rbCATurmaSim = new javax.swing.JRadioButton();
        rbCATurmaNao = new javax.swing.JRadioButton();
        jPanel17 = new javax.swing.JPanel();
        rbExcluirUsuarioSim = new javax.swing.JRadioButton();
        rbExcluirUsuarioNao = new javax.swing.JRadioButton();
        jPanel18 = new javax.swing.JPanel();
        rbExcluirTurmaSim = new javax.swing.JRadioButton();
        rbExcluirTurmaNao = new javax.swing.JRadioButton();
        jPanel19 = new javax.swing.JPanel();
        rbCADisciplinaSim = new javax.swing.JRadioButton();
        rbCADisciplinaNao = new javax.swing.JRadioButton();
        jPanel20 = new javax.swing.JPanel();
        rbEmitirDocumentosSim = new javax.swing.JRadioButton();
        rbEmitirDocumentosNao = new javax.swing.JRadioButton();
        jPanel21 = new javax.swing.JPanel();
        rbCAFornecedorSim = new javax.swing.JRadioButton();
        rbCAFornecedorNao = new javax.swing.JRadioButton();
        jPanel22 = new javax.swing.JPanel();
        rbExcluirDisciplinaSim = new javax.swing.JRadioButton();
        rbExcluirDisciplinaNao = new javax.swing.JRadioButton();
        jPanel23 = new javax.swing.JPanel();
        rbCABensConsumorSim = new javax.swing.JRadioButton();
        rbCABensConsumoNao = new javax.swing.JRadioButton();
        jPanel24 = new javax.swing.JPanel();
        rbExcluirFornecedoresSim = new javax.swing.JRadioButton();
        rbExcluirFornecedoresNao = new javax.swing.JRadioButton();
        jPanel25 = new javax.swing.JPanel();
        rbExcluirBensConsumoSim = new javax.swing.JRadioButton();
        rbExcluirBensConsumoNao = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setMinimumSize(new java.awt.Dimension(945, 450));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(945, 502));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Login/Senha", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setOpaque(false);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Login");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Senha");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Repetir Senha");

        checkUsuarioMaster.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkUsuarioMaster.setForeground(new java.awt.Color(255, 255, 255));
        checkUsuarioMaster.setText("Usuário Máster");
        checkUsuarioMaster.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtRepetirSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkUsuarioMaster, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRepetirSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkUsuarioMaster)))
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Privilégios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setOpaque(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastrar/Atualizar Aluno", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setOpaque(false);

        buttonGroup1.add(rbCAAlunoSim);
        rbCAAlunoSim.setForeground(new java.awt.Color(255, 255, 255));
        rbCAAlunoSim.setSelected(true);
        rbCAAlunoSim.setText("Sim");
        rbCAAlunoSim.setOpaque(false);

        buttonGroup1.add(rbCAAlunoNao);
        rbCAAlunoNao.setForeground(new java.awt.Color(255, 255, 255));
        rbCAAlunoNao.setText("Não");
        rbCAAlunoNao.setOpaque(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbCAAlunoSim)
                .addGap(18, 18, 18)
                .addComponent(rbCAAlunoNao)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCAAlunoSim)
                    .addComponent(rbCAAlunoNao))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastrar/Atualizar Professor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel4.setOpaque(false);

        buttonGroup2.add(rbCAProfessorSim);
        rbCAProfessorSim.setForeground(new java.awt.Color(255, 255, 255));
        rbCAProfessorSim.setSelected(true);
        rbCAProfessorSim.setText("Sim");
        rbCAProfessorSim.setOpaque(false);

        buttonGroup2.add(rbCAProfessorNao);
        rbCAProfessorNao.setForeground(new java.awt.Color(255, 255, 255));
        rbCAProfessorNao.setText("Não");
        rbCAProfessorNao.setOpaque(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbCAProfessorSim)
                .addGap(18, 18, 18)
                .addComponent(rbCAProfessorNao)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCAProfessorSim)
                    .addComponent(rbCAProfessorNao))
                .addContainerGap())
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastrar/Atualizar Funcionário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel8.setOpaque(false);

        buttonGroup3.add(rbCAFuncionarioSim);
        rbCAFuncionarioSim.setForeground(new java.awt.Color(255, 255, 255));
        rbCAFuncionarioSim.setSelected(true);
        rbCAFuncionarioSim.setText("Sim");
        rbCAFuncionarioSim.setOpaque(false);

        buttonGroup3.add(rbCAFuncionarioNao);
        rbCAFuncionarioNao.setForeground(new java.awt.Color(255, 255, 255));
        rbCAFuncionarioNao.setText("Não");
        rbCAFuncionarioNao.setOpaque(false);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbCAFuncionarioSim)
                .addGap(18, 18, 18)
                .addComponent(rbCAFuncionarioNao)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCAFuncionarioSim)
                    .addComponent(rbCAFuncionarioNao))
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Controle Financeiro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel6.setOpaque(false);

        buttonGroup5.add(rbControleFinanceiroSim);
        rbControleFinanceiroSim.setForeground(new java.awt.Color(255, 255, 255));
        rbControleFinanceiroSim.setText("Sim");
        rbControleFinanceiroSim.setOpaque(false);

        buttonGroup5.add(rbControleFinanceiroNao);
        rbControleFinanceiroNao.setForeground(new java.awt.Color(255, 255, 255));
        rbControleFinanceiroNao.setSelected(true);
        rbControleFinanceiroNao.setText("Não");
        rbControleFinanceiroNao.setOpaque(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbControleFinanceiroSim)
                .addGap(18, 18, 18)
                .addComponent(rbControleFinanceiroNao)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbControleFinanceiroSim)
                    .addComponent(rbControleFinanceiroNao))
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Excluir Aluno", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel7.setOpaque(false);

        buttonGroup6.add(rbExcluirAlunoSim);
        rbExcluirAlunoSim.setForeground(new java.awt.Color(255, 255, 255));
        rbExcluirAlunoSim.setText("Sim");
        rbExcluirAlunoSim.setOpaque(false);

        buttonGroup6.add(rbExcluirAlunoNao);
        rbExcluirAlunoNao.setForeground(new java.awt.Color(255, 255, 255));
        rbExcluirAlunoNao.setSelected(true);
        rbExcluirAlunoNao.setText("Não");
        rbExcluirAlunoNao.setOpaque(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbExcluirAlunoSim)
                .addGap(18, 18, 18)
                .addComponent(rbExcluirAlunoNao)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbExcluirAlunoSim)
                    .addComponent(rbExcluirAlunoNao))
                .addContainerGap())
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastrar Usuário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel9.setOpaque(false);

        buttonGroup4.add(rbCadastrarUsuarioSim);
        rbCadastrarUsuarioSim.setForeground(new java.awt.Color(255, 255, 255));
        rbCadastrarUsuarioSim.setSelected(true);
        rbCadastrarUsuarioSim.setText("Sim");
        rbCadastrarUsuarioSim.setOpaque(false);

        buttonGroup4.add(rbCadastrarUsuarioNao);
        rbCadastrarUsuarioNao.setForeground(new java.awt.Color(255, 255, 255));
        rbCadastrarUsuarioNao.setText("Não");
        rbCadastrarUsuarioNao.setOpaque(false);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbCadastrarUsuarioSim)
                .addGap(18, 18, 18)
                .addComponent(rbCadastrarUsuarioNao)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCadastrarUsuarioSim)
                    .addComponent(rbCadastrarUsuarioNao))
                .addContainerGap())
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Excluir Professor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel10.setOpaque(false);

        buttonGroup7.add(rbExcluirProfessorSim);
        rbExcluirProfessorSim.setForeground(new java.awt.Color(255, 255, 255));
        rbExcluirProfessorSim.setText("Sim");
        rbExcluirProfessorSim.setOpaque(false);

        buttonGroup7.add(rbExcluirProfessorNao);
        rbExcluirProfessorNao.setForeground(new java.awt.Color(255, 255, 255));
        rbExcluirProfessorNao.setSelected(true);
        rbExcluirProfessorNao.setText("Não");
        rbExcluirProfessorNao.setOpaque(false);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbExcluirProfessorSim)
                .addGap(18, 18, 18)
                .addComponent(rbExcluirProfessorNao)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbExcluirProfessorSim)
                    .addComponent(rbExcluirProfessorNao))
                .addContainerGap())
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Excluir Funcionário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel11.setOpaque(false);

        buttonGroup8.add(rbExcluirFuncionarioSim);
        rbExcluirFuncionarioSim.setForeground(new java.awt.Color(255, 255, 255));
        rbExcluirFuncionarioSim.setText("Sim");
        rbExcluirFuncionarioSim.setOpaque(false);

        buttonGroup8.add(rbExcluirFuncionarioNao);
        rbExcluirFuncionarioNao.setForeground(new java.awt.Color(255, 255, 255));
        rbExcluirFuncionarioNao.setSelected(true);
        rbExcluirFuncionarioNao.setText("Não");
        rbExcluirFuncionarioNao.setOpaque(false);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbExcluirFuncionarioSim)
                .addGap(18, 18, 18)
                .addComponent(rbExcluirFuncionarioNao)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbExcluirFuncionarioSim)
                    .addComponent(rbExcluirFuncionarioNao))
                .addContainerGap())
        );

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Emitir Relatórios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel15.setOpaque(false);

        buttonGroup10.add(rbEmitirRelatoriosSim);
        rbEmitirRelatoriosSim.setForeground(new java.awt.Color(255, 255, 255));
        rbEmitirRelatoriosSim.setText("Sim");
        rbEmitirRelatoriosSim.setOpaque(false);

        buttonGroup10.add(rbEmitirRelatoriosNao);
        rbEmitirRelatoriosNao.setForeground(new java.awt.Color(255, 255, 255));
        rbEmitirRelatoriosNao.setSelected(true);
        rbEmitirRelatoriosNao.setText("Não");
        rbEmitirRelatoriosNao.setOpaque(false);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbEmitirRelatoriosSim)
                .addGap(18, 18, 18)
                .addComponent(rbEmitirRelatoriosNao)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbEmitirRelatoriosSim)
                    .addComponent(rbEmitirRelatoriosNao))
                .addContainerGap())
        );

        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastrar/Alterar Turma", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel16.setOpaque(false);

        buttonGroup11.add(rbCATurmaSim);
        rbCATurmaSim.setForeground(new java.awt.Color(255, 255, 255));
        rbCATurmaSim.setSelected(true);
        rbCATurmaSim.setText("Sim");
        rbCATurmaSim.setOpaque(false);

        buttonGroup11.add(rbCATurmaNao);
        rbCATurmaNao.setForeground(new java.awt.Color(255, 255, 255));
        rbCATurmaNao.setText("Não");
        rbCATurmaNao.setOpaque(false);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbCATurmaSim)
                .addGap(18, 18, 18)
                .addComponent(rbCATurmaNao)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCATurmaSim)
                    .addComponent(rbCATurmaNao))
                .addContainerGap())
        );

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Excluir Usuário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel17.setOpaque(false);

        buttonGroup9.add(rbExcluirUsuarioSim);
        rbExcluirUsuarioSim.setForeground(new java.awt.Color(255, 255, 255));
        rbExcluirUsuarioSim.setText("Sim");
        rbExcluirUsuarioSim.setOpaque(false);

        buttonGroup9.add(rbExcluirUsuarioNao);
        rbExcluirUsuarioNao.setForeground(new java.awt.Color(255, 255, 255));
        rbExcluirUsuarioNao.setSelected(true);
        rbExcluirUsuarioNao.setText("Não");
        rbExcluirUsuarioNao.setOpaque(false);

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbExcluirUsuarioSim)
                .addGap(18, 18, 18)
                .addComponent(rbExcluirUsuarioNao)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbExcluirUsuarioSim)
                    .addComponent(rbExcluirUsuarioNao))
                .addContainerGap())
        );

        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Excluir Turma", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel18.setOpaque(false);

        buttonGroup13.add(rbExcluirTurmaSim);
        rbExcluirTurmaSim.setForeground(new java.awt.Color(255, 255, 255));
        rbExcluirTurmaSim.setText("Sim");
        rbExcluirTurmaSim.setOpaque(false);

        buttonGroup13.add(rbExcluirTurmaNao);
        rbExcluirTurmaNao.setForeground(new java.awt.Color(255, 255, 255));
        rbExcluirTurmaNao.setSelected(true);
        rbExcluirTurmaNao.setText("Não");
        rbExcluirTurmaNao.setOpaque(false);

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbExcluirTurmaSim)
                .addGap(18, 18, 18)
                .addComponent(rbExcluirTurmaNao)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbExcluirTurmaSim)
                    .addComponent(rbExcluirTurmaNao))
                .addContainerGap())
        );

        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastrar/Alterar Disciplina", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel19.setOpaque(false);

        buttonGroup12.add(rbCADisciplinaSim);
        rbCADisciplinaSim.setForeground(new java.awt.Color(255, 255, 255));
        rbCADisciplinaSim.setSelected(true);
        rbCADisciplinaSim.setText("Sim");
        rbCADisciplinaSim.setOpaque(false);

        buttonGroup12.add(rbCADisciplinaNao);
        rbCADisciplinaNao.setForeground(new java.awt.Color(255, 255, 255));
        rbCADisciplinaNao.setText("Não");
        rbCADisciplinaNao.setOpaque(false);

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbCADisciplinaSim)
                .addGap(18, 18, 18)
                .addComponent(rbCADisciplinaNao)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCADisciplinaSim)
                    .addComponent(rbCADisciplinaNao))
                .addContainerGap())
        );

        jPanel20.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Emitir Documentos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel20.setOpaque(false);

        buttonGroup15.add(rbEmitirDocumentosSim);
        rbEmitirDocumentosSim.setForeground(new java.awt.Color(255, 255, 255));
        rbEmitirDocumentosSim.setSelected(true);
        rbEmitirDocumentosSim.setText("Sim");
        rbEmitirDocumentosSim.setOpaque(false);

        buttonGroup15.add(rbEmitirDocumentosNao);
        rbEmitirDocumentosNao.setForeground(new java.awt.Color(255, 255, 255));
        rbEmitirDocumentosNao.setText("Não");
        rbEmitirDocumentosNao.setOpaque(false);

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbEmitirDocumentosSim)
                .addGap(18, 18, 18)
                .addComponent(rbEmitirDocumentosNao)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbEmitirDocumentosSim)
                    .addComponent(rbEmitirDocumentosNao))
                .addContainerGap())
        );

        jPanel21.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastrar/Atualizar Fornecedores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel21.setOpaque(false);

        buttonGroup16.add(rbCAFornecedorSim);
        rbCAFornecedorSim.setForeground(new java.awt.Color(255, 255, 255));
        rbCAFornecedorSim.setSelected(true);
        rbCAFornecedorSim.setText("Sim");
        rbCAFornecedorSim.setOpaque(false);

        buttonGroup16.add(rbCAFornecedorNao);
        rbCAFornecedorNao.setForeground(new java.awt.Color(255, 255, 255));
        rbCAFornecedorNao.setText("Não");
        rbCAFornecedorNao.setOpaque(false);

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbCAFornecedorSim)
                .addGap(18, 18, 18)
                .addComponent(rbCAFornecedorNao)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCAFornecedorSim)
                    .addComponent(rbCAFornecedorNao))
                .addContainerGap())
        );

        jPanel22.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Excluir Disciplina", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel22.setOpaque(false);

        buttonGroup14.add(rbExcluirDisciplinaSim);
        rbExcluirDisciplinaSim.setForeground(new java.awt.Color(255, 255, 255));
        rbExcluirDisciplinaSim.setText("Sim");
        rbExcluirDisciplinaSim.setOpaque(false);

        buttonGroup14.add(rbExcluirDisciplinaNao);
        rbExcluirDisciplinaNao.setForeground(new java.awt.Color(255, 255, 255));
        rbExcluirDisciplinaNao.setSelected(true);
        rbExcluirDisciplinaNao.setText("Não");
        rbExcluirDisciplinaNao.setOpaque(false);

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbExcluirDisciplinaSim)
                .addGap(18, 18, 18)
                .addComponent(rbExcluirDisciplinaNao)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbExcluirDisciplinaSim)
                    .addComponent(rbExcluirDisciplinaNao))
                .addContainerGap())
        );

        jPanel23.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastrar/Aterar Bens Patrimoniais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel23.setOpaque(false);

        buttonGroup17.add(rbCABensConsumorSim);
        rbCABensConsumorSim.setForeground(new java.awt.Color(255, 255, 255));
        rbCABensConsumorSim.setSelected(true);
        rbCABensConsumorSim.setText("Sim");
        rbCABensConsumorSim.setOpaque(false);

        buttonGroup17.add(rbCABensConsumoNao);
        rbCABensConsumoNao.setForeground(new java.awt.Color(255, 255, 255));
        rbCABensConsumoNao.setText("Não");
        rbCABensConsumoNao.setOpaque(false);

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbCABensConsumorSim)
                .addGap(18, 18, 18)
                .addComponent(rbCABensConsumoNao)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCABensConsumorSim)
                    .addComponent(rbCABensConsumoNao))
                .addContainerGap())
        );

        jPanel24.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Excluir Fornecedores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel24.setOpaque(false);

        buttonGroup18.add(rbExcluirFornecedoresSim);
        rbExcluirFornecedoresSim.setForeground(new java.awt.Color(255, 255, 255));
        rbExcluirFornecedoresSim.setText("Sim");
        rbExcluirFornecedoresSim.setOpaque(false);

        buttonGroup18.add(rbExcluirFornecedoresNao);
        rbExcluirFornecedoresNao.setForeground(new java.awt.Color(255, 255, 255));
        rbExcluirFornecedoresNao.setSelected(true);
        rbExcluirFornecedoresNao.setText("Não");
        rbExcluirFornecedoresNao.setOpaque(false);

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbExcluirFornecedoresSim)
                .addGap(18, 18, 18)
                .addComponent(rbExcluirFornecedoresNao)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel24Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbExcluirFornecedoresSim)
                    .addComponent(rbExcluirFornecedoresNao))
                .addContainerGap())
        );

        jPanel25.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Excluir Bens Patrimoniais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel25.setOpaque(false);

        buttonGroup19.add(rbExcluirBensConsumoSim);
        rbExcluirBensConsumoSim.setForeground(new java.awt.Color(255, 255, 255));
        rbExcluirBensConsumoSim.setText("Sim");
        rbExcluirBensConsumoSim.setOpaque(false);

        buttonGroup19.add(rbExcluirBensConsumoNao);
        rbExcluirBensConsumoNao.setForeground(new java.awt.Color(255, 255, 255));
        rbExcluirBensConsumoNao.setSelected(true);
        rbExcluirBensConsumoNao.setText("Não");
        rbExcluirBensConsumoNao.setOpaque(false);

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbExcluirBensConsumoSim)
                .addGap(18, 18, 18)
                .addComponent(rbExcluirBensConsumoNao)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel25Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbExcluirBensConsumoSim)
                    .addComponent(rbExcluirBensConsumoNao))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public JCheckBox getCheckUsuarioMaster() {
        return checkUsuarioMaster;
    }

    public JRadioButton getRbCAAlunoNao() {
        return rbCAAlunoNao;
    }

    public JRadioButton getRbCAAlunoSim() {
        return rbCAAlunoSim;
    }

    public JRadioButton getRbCABensConsumoNao() {
        return rbCABensConsumoNao;
    }

    public JRadioButton getRbCABensConsumorSim() {
        return rbCABensConsumorSim;
    }

    public JRadioButton getRbCADisciplinaNao() {
        return rbCADisciplinaNao;
    }

    public JRadioButton getRbCADisciplinaSim() {
        return rbCADisciplinaSim;
    }

    public JRadioButton getRbCAFornecedorNao() {
        return rbCAFornecedorNao;
    }

    public JRadioButton getRbCAFornecedorSim() {
        return rbCAFornecedorSim;
    }

    public JRadioButton getRbCAFuncionarioNao() {
        return rbCAFuncionarioNao;
    }

    public JRadioButton getRbCAFuncionarioSim() {
        return rbCAFuncionarioSim;
    }

    public JRadioButton getRbCAProfessorNao() {
        return rbCAProfessorNao;
    }

    public JRadioButton getRbCAProfessorSim() {
        return rbCAProfessorSim;
    }

    public JRadioButton getRbCATurmaNao() {
        return rbCATurmaNao;
    }

    public JRadioButton getRbCATurmaSim() {
        return rbCATurmaSim;
    }

    public JRadioButton getRbCadastrarUsuarioNao() {
        return rbCadastrarUsuarioNao;
    }

    public JRadioButton getRbCadastrarUsuarioSim() {
        return rbCadastrarUsuarioSim;
    }

    public JRadioButton getRbControleFinanceiroNao() {
        return rbControleFinanceiroNao;
    }

    public JRadioButton getRbControleFinanceiroSim() {
        return rbControleFinanceiroSim;
    }

    public JRadioButton getRbEmitirDocumentosNao() {
        return rbEmitirDocumentosNao;
    }

    public JRadioButton getRbEmitirDocumentosSim() {
        return rbEmitirDocumentosSim;
    }

    public JRadioButton getRbEmitirRelatoriosNao() {
        return rbEmitirRelatoriosNao;
    }

    public JRadioButton getRbEmitirRelatoriosSim() {
        return rbEmitirRelatoriosSim;
    }

    public JRadioButton getRbExcluirAlunoNao() {
        return rbExcluirAlunoNao;
    }

    public JRadioButton getRbExcluirAlunoSim() {
        return rbExcluirAlunoSim;
    }

    public JRadioButton getRbExcluirBensConsumoNao() {
        return rbExcluirBensConsumoNao;
    }

    public JRadioButton getRbExcluirBensConsumoSim() {
        return rbExcluirBensConsumoSim;
    }

    public JRadioButton getRbExcluirDisciplinaNao() {
        return rbExcluirDisciplinaNao;
    }

    public JRadioButton getRbExcluirDisciplinaSim() {
        return rbExcluirDisciplinaSim;
    }

    public JRadioButton getRbExcluirFornecedoresNao() {
        return rbExcluirFornecedoresNao;
    }

    public JRadioButton getRbExcluirFornecedoresSim() {
        return rbExcluirFornecedoresSim;
    }

    public JRadioButton getRbExcluirFuncionarioNao() {
        return rbExcluirFuncionarioNao;
    }

    public JRadioButton getRbExcluirFuncionarioSim() {
        return rbExcluirFuncionarioSim;
    }

    public JRadioButton getRbExcluirProfessorNao() {
        return rbExcluirProfessorNao;
    }

    public JRadioButton getRbExcluirProfessorSim() {
        return rbExcluirProfessorSim;
    }

    public JRadioButton getRbExcluirTurmaNao() {
        return rbExcluirTurmaNao;
    }

    public JRadioButton getRbExcluirTurmaSim() {
        return rbExcluirTurmaSim;
    }

    public JRadioButton getRbExcluirUsuarioNao() {
        return rbExcluirUsuarioNao;
    }

    public JRadioButton getRbExcluirUsuarioSim() {
        return rbExcluirUsuarioSim;
    }

    public JTextField getTxtLogin() {
        return txtLogin;
    }

    public JPasswordField getTxtRepetirSenha() {
        return txtRepetirSenha;
    }

    public JPasswordField getTxtSenha() {
        return txtSenha;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup12;
    private javax.swing.ButtonGroup buttonGroup13;
    private javax.swing.ButtonGroup buttonGroup14;
    private javax.swing.ButtonGroup buttonGroup15;
    private javax.swing.ButtonGroup buttonGroup16;
    private javax.swing.ButtonGroup buttonGroup17;
    private javax.swing.ButtonGroup buttonGroup18;
    private javax.swing.ButtonGroup buttonGroup19;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JCheckBox checkUsuarioMaster;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton rbCAAlunoNao;
    private javax.swing.JRadioButton rbCAAlunoSim;
    private javax.swing.JRadioButton rbCABensConsumoNao;
    private javax.swing.JRadioButton rbCABensConsumorSim;
    private javax.swing.JRadioButton rbCADisciplinaNao;
    private javax.swing.JRadioButton rbCADisciplinaSim;
    private javax.swing.JRadioButton rbCAFornecedorNao;
    private javax.swing.JRadioButton rbCAFornecedorSim;
    private javax.swing.JRadioButton rbCAFuncionarioNao;
    private javax.swing.JRadioButton rbCAFuncionarioSim;
    private javax.swing.JRadioButton rbCAProfessorNao;
    private javax.swing.JRadioButton rbCAProfessorSim;
    private javax.swing.JRadioButton rbCATurmaNao;
    private javax.swing.JRadioButton rbCATurmaSim;
    private javax.swing.JRadioButton rbCadastrarUsuarioNao;
    private javax.swing.JRadioButton rbCadastrarUsuarioSim;
    private javax.swing.JRadioButton rbControleFinanceiroNao;
    private javax.swing.JRadioButton rbControleFinanceiroSim;
    private javax.swing.JRadioButton rbEmitirDocumentosNao;
    private javax.swing.JRadioButton rbEmitirDocumentosSim;
    private javax.swing.JRadioButton rbEmitirRelatoriosNao;
    private javax.swing.JRadioButton rbEmitirRelatoriosSim;
    private javax.swing.JRadioButton rbExcluirAlunoNao;
    private javax.swing.JRadioButton rbExcluirAlunoSim;
    private javax.swing.JRadioButton rbExcluirBensConsumoNao;
    private javax.swing.JRadioButton rbExcluirBensConsumoSim;
    private javax.swing.JRadioButton rbExcluirDisciplinaNao;
    private javax.swing.JRadioButton rbExcluirDisciplinaSim;
    private javax.swing.JRadioButton rbExcluirFornecedoresNao;
    private javax.swing.JRadioButton rbExcluirFornecedoresSim;
    private javax.swing.JRadioButton rbExcluirFuncionarioNao;
    private javax.swing.JRadioButton rbExcluirFuncionarioSim;
    private javax.swing.JRadioButton rbExcluirProfessorNao;
    private javax.swing.JRadioButton rbExcluirProfessorSim;
    private javax.swing.JRadioButton rbExcluirTurmaNao;
    private javax.swing.JRadioButton rbExcluirTurmaSim;
    private javax.swing.JRadioButton rbExcluirUsuarioNao;
    private javax.swing.JRadioButton rbExcluirUsuarioSim;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtRepetirSenha;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
