/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.siseduc.view;

import br.com.siseduc.Siseduc;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.JToolBar;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juan Soares
 */
public class TelaPesquisaProfessor extends javax.swing.JDialog {

    /**
     *
     */
    private static final long serialVersionUID = 905747677817359677L;
    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;
    /**
     *
     */
    private final DefaultTableModel tabelaPadrao = new DefaultTableModel();
    /**
     * Creates new form TelaCadastroPesquisaAluno
     *
     * @param parent super classe
     * @param modal informa se a janela é modal
     */
    public TelaPesquisaProfessor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuFlutuante = new javax.swing.JPopupMenu();
        jmiEditar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmiGerarDiarioClasse = new javax.swing.JMenuItem();
        jmiDeclaracao = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        barraDeFerramentas = new javax.swing.JToolBar();
        btnNovoProfessor = new javax.swing.JButton();
        btnEditarProfessor = new javax.swing.JButton();
        btnExcluirProfessor = new javax.swing.JButton();
        btnRelatorios = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jcbOrdenar = new javax.swing.JComboBox<>();
        txtPesquisar = new javax.swing.JTextField();
        lbOrdenar = new javax.swing.JLabel();
        lbPesquisar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaListarProfessor = new javax.swing.JTable() {
            public boolean isCellEditable(int rowIndex, int vColIndex) {
                return false;
            }
        };

        menuFlutuante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jmiEditar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jmiEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/compose-mini.png"))); // NOI18N
        jmiEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuFlutuante.add(jmiEditar);
        menuFlutuante.add(jSeparator1);

        jmiGerarDiarioClasse.setText("Gerar Diário de Classe");
        menuFlutuante.add(jmiGerarDiarioClasse);

        jmiDeclaracao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuFlutuante.add(jmiDeclaracao);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle(Siseduc.TITULO);
        setIconImage(null);
        setMinimumSize(new java.awt.Dimension(871, 488));

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 204));

        barraDeFerramentas.setBorder(null);
        barraDeFerramentas.setFloatable(false);
        barraDeFerramentas.setRollover(true);

        btnNovoProfessor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnNovoProfessor.setForeground(new java.awt.Color(255, 255, 255));
        btnNovoProfessor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/university.png"))); // NOI18N
        btnNovoProfessor.setText("Novo");
        btnNovoProfessor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNovoProfessor.setFocusable(false);
        btnNovoProfessor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNovoProfessor.setPreferredSize(new java.awt.Dimension(90, 90));
        btnNovoProfessor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barraDeFerramentas.add(btnNovoProfessor);

        btnEditarProfessor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEditarProfessor.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarProfessor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/compose.png"))); // NOI18N
        btnEditarProfessor.setText("Editar");
        btnEditarProfessor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditarProfessor.setFocusable(false);
        btnEditarProfessor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditarProfessor.setPreferredSize(new java.awt.Dimension(90, 90));
        btnEditarProfessor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barraDeFerramentas.add(btnEditarProfessor);

        btnExcluirProfessor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnExcluirProfessor.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluirProfessor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ios7-close-outline.png"))); // NOI18N
        btnExcluirProfessor.setText("Excluir");
        btnExcluirProfessor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluirProfessor.setFocusable(false);
        btnExcluirProfessor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcluirProfessor.setPreferredSize(new java.awt.Dimension(90, 90));
        btnExcluirProfessor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barraDeFerramentas.add(btnExcluirProfessor);

        btnRelatorios.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRelatorios.setForeground(new java.awt.Color(255, 255, 255));
        btnRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ios7-paper-outline.png"))); // NOI18N
        btnRelatorios.setText("Relatórios");
        btnRelatorios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRelatorios.setFocusable(false);
        btnRelatorios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRelatorios.setPreferredSize(new java.awt.Dimension(90, 90));
        btnRelatorios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barraDeFerramentas.add(btnRelatorios);

        btnSair.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 255, 255));
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/log-out.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSair.setFocusable(false);
        btnSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSair.setPreferredSize(new java.awt.Dimension(90, 90));
        btnSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barraDeFerramentas.add(btnSair);

        jcbOrdenar.setMaximumRowCount(5);
        jcbOrdenar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matricula", "Nome", "Data Cadastro", "Data Nascimento", "Naturalidade", "Estado", "Cidade", "Bairro" }));

        lbOrdenar.setForeground(new java.awt.Color(255, 255, 255));
        lbOrdenar.setText("Ordenar por:");

        lbPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        lbPesquisar.setText("Pesquisa por nome");

        tabelaListarProfessor.setModel(tabelaPadrao);
        tabelaListarProfessor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabelaListarProfessor.setShowHorizontalLines(false);
        tabelaListarProfessor.setShowVerticalLines(false);
        tabelaListarProfessor.getTableHeader().setReorderingAllowed(false);
        tabelaListarProfessor.setUpdateSelectionOnSort(false);
        tabelaListarProfessor.setVerifyInputWhenFocusTarget(false);
        this.criarTabela();
        jScrollPane1.setViewportView(tabelaListarProfessor);

        jDesktopPane1.setLayer(barraDeFerramentas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jcbOrdenar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtPesquisar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lbOrdenar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lbPesquisar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(barraDeFerramentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbOrdenar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbOrdenar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(lbPesquisar)
                                .addGap(0, 121, Short.MAX_VALUE))
                            .addComponent(txtPesquisar))))
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(barraDeFerramentas, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbOrdenar)
                            .addComponent(lbPesquisar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbOrdenar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * 
     */
    public void criarTabela() {
        tabelaPadrao.addColumn("Matrícula");
        tabelaPadrao.addColumn("Nome");
        tabelaPadrao.addColumn("Telefone");
        tabelaPadrao.addColumn("Celular");
        tabelaPadrao.addColumn("Email");
        
        tabelaListarProfessor.getColumnModel().getColumn(0).setPreferredWidth(5);
        tabelaListarProfessor.getColumnModel().getColumn(2).setPreferredWidth(5);
        tabelaListarProfessor.getColumnModel().getColumn(3).setPreferredWidth(5);
        
    }
    
    public JButton getBtnEditarProfessor() {
        return btnEditarProfessor;
    }

    public JButton getBtnExcluirProfessor() {
        return btnExcluirProfessor;
    }

    public JButton getBtnNovoProfessor() {
        return btnNovoProfessor;
    }

    public JButton getBtnRelatorios() {
        return btnRelatorios;
    }

    public JButton getBtnSair() {
        return btnSair;
    }

    public JComboBox<String> getJcbOrdenar() {
        return jcbOrdenar;
    }

    public JTable getTabelaListarProfessor() {
        return tabelaListarProfessor;
    }

    public JTextField getTxtPesquisar() {
        return txtPesquisar;
    }

    public DefaultTableModel getTabelaPadrao() {
        return tabelaPadrao;
    }

    public JMenuItem getJmiDeclaracao() {
        return jmiDeclaracao;
    }

    public JMenuItem getJmiEditar() {
        return jmiEditar;
    }

    public JPopupMenu getMenuFlutuante() {
        return menuFlutuante;
    }

    public JMenuItem getJmiGerarDiarioClasse() {
        return jmiGerarDiarioClasse;
    }

    public JToolBar getBarraDeFerramentas() {
        return barraDeFerramentas;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar barraDeFerramentas;
    private javax.swing.JButton btnEditarProfessor;
    private javax.swing.JButton btnExcluirProfessor;
    private javax.swing.JButton btnNovoProfessor;
    private javax.swing.JButton btnRelatorios;
    private javax.swing.JButton btnSair;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JComboBox<String> jcbOrdenar;
    private javax.swing.JMenuItem jmiDeclaracao;
    private javax.swing.JMenuItem jmiEditar;
    private javax.swing.JMenuItem jmiGerarDiarioClasse;
    private javax.swing.JLabel lbOrdenar;
    private javax.swing.JLabel lbPesquisar;
    private javax.swing.JPopupMenu menuFlutuante;
    private javax.swing.JTable tabelaListarProfessor;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables

    private final int returnStatus = RET_CANCEL;
}
