/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.siseduc.view;

import br.com.siseduc.Siseduc;
import br.com.siseduc.model.bo.PessoaBO;
import br.com.siseduc.model.dao.Arquivo;
import br.com.siseduc.model.vo.Estados;
import br.com.siseduc.model.vo.Fornecedor;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;

/**
 *
 * @author Juan Soares
 */
public class TelaCadastroFornecedor extends javax.swing.JDialog {

    /**
    * 
    */
    private static final long serialVersionUID = -7592275759027156307L;
    /**
    * A return status code - returned if Cancel button has been pressed
    */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;
    
    /**
     * Creates new form TelaCadastroAluno
     * @param parent super classe
     * @param modal informa se a janela é modal
     */
    public TelaCadastroFornecedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoTipo = new javax.swing.ButtonGroup();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        txtNomeDesabilitado = new javax.swing.JTextField();
        lbNomeDesabilitado = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        lbMatricula = new javax.swing.JLabel();
        jtPainelCadastro = new javax.swing.JTabbedPane();
        painelDadosDoFornecedor = new javax.swing.JPanel();
        painelDadosPessoaisFornecedor = new javax.swing.JPanel();
        txtNomeFantasia = new javax.swing.JTextField();
        lbNomeFantasia = new javax.swing.JLabel();
        painelTipo = new javax.swing.JPanel();
        rbPessoaFisica = new javax.swing.JRadioButton();
        rbPessoaJuridica = new javax.swing.JRadioButton();
        lbDataFundacao = new javax.swing.JLabel();
        lbRazaoSocial = new javax.swing.JLabel();
        txtRazaoSocial = new javax.swing.JTextField();
        lbSegmento = new javax.swing.JLabel();
        txtSegmento = new javax.swing.JTextField();
        txtDataFundacao = new javax.swing.JFormattedTextField();
        painelLogo = new javax.swing.JPanel();
        lbLogo = new javax.swing.JLabel();
        lbIE = new javax.swing.JLabel();
        lbCpfCnpj = new javax.swing.JLabel();
        txtSite = new javax.swing.JTextField();
        lbSite = new javax.swing.JLabel();
        txtIE = new javax.swing.JTextField();
        txtCpfCnpj = new javax.swing.JTextField();
        painelEnderecoProfessor = new javax.swing.JPanel();
        txtEndereco = new javax.swing.JTextField();
        lbEndereco = new javax.swing.JLabel();
        txtComplementoEndereco = new javax.swing.JTextField();
        lbComplementoEndereco = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        lbCidade = new javax.swing.JLabel();
        jcbUfResidencia = new javax.swing.JComboBox<>();
        lbUfResidencia = new javax.swing.JLabel();
        txtCep = new javax.swing.JFormattedTextField();
        txtTelefone = new javax.swing.JFormattedTextField();
        lbCep = new javax.swing.JLabel();
        lbTelefone = new javax.swing.JLabel();
        lbCelular = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        txtCelular = new javax.swing.JFormattedTextField();
        txtEmail = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        lbBairro = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle(Siseduc.TITULO);
        setIconImage(new ImageIcon(getClass().getResource("/images/icone.png")).getImage());
        setResizable(false);

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 204));

        txtNomeDesabilitado.setEditable(false);
        txtNomeDesabilitado.setBackground(new java.awt.Color(204, 204, 204));
        txtNomeDesabilitado.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N

        lbNomeDesabilitado.setForeground(new java.awt.Color(255, 255, 255));
        lbNomeDesabilitado.setText("Nome do(a) Fornecedor(a)");

        txtMatricula.setEditable(false);
        txtMatricula.setBackground(new java.awt.Color(204, 204, 204));
        txtMatricula.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N

        lbMatricula.setForeground(new java.awt.Color(255, 255, 255));
        lbMatricula.setText("Matrícula");

        jtPainelCadastro.setBackground(new java.awt.Color(0, 0, 204));
        jtPainelCadastro.setPreferredSize(new java.awt.Dimension(914, 300));

        painelDadosDoFornecedor.setBackground(new java.awt.Color(51, 51, 51));
        painelDadosDoFornecedor.setOpaque(false);

        painelDadosPessoaisFornecedor.setBackground(new java.awt.Color(102, 102, 102));
        painelDadosPessoaisFornecedor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Empresa", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        painelDadosPessoaisFornecedor.setOpaque(false);

        lbNomeFantasia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbNomeFantasia.setForeground(new java.awt.Color(255, 255, 255));
        lbNomeFantasia.setLabelFor(txtNomeFantasia);
        lbNomeFantasia.setText("Nome Fantasia (Obrigatório)");

        painelTipo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        painelTipo.setOpaque(false);

        grupoTipo.add(rbPessoaFisica);
        rbPessoaFisica.setForeground(new java.awt.Color(255, 255, 255));
        rbPessoaFisica.setSelected(true);
        rbPessoaFisica.setText("Pessoa Física");
        rbPessoaFisica.setOpaque(false);

        grupoTipo.add(rbPessoaJuridica);
        rbPessoaJuridica.setForeground(new java.awt.Color(255, 255, 255));
        rbPessoaJuridica.setText("Pessoa Jurídica");
        rbPessoaJuridica.setOpaque(false);

        javax.swing.GroupLayout painelTipoLayout = new javax.swing.GroupLayout(painelTipo);
        painelTipo.setLayout(painelTipoLayout);
        painelTipoLayout.setHorizontalGroup(
            painelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTipoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbPessoaFisica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(rbPessoaJuridica)
                .addContainerGap())
        );
        painelTipoLayout.setVerticalGroup(
            painelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelTipoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(painelTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbPessoaFisica)
                    .addComponent(rbPessoaJuridica)))
        );

        painelTipoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {rbPessoaFisica, rbPessoaJuridica});

        lbDataFundacao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbDataFundacao.setForeground(new java.awt.Color(255, 255, 255));
        lbDataFundacao.setLabelFor(txtDataFundacao);
        lbDataFundacao.setText("Data Fundação");

        lbRazaoSocial.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbRazaoSocial.setForeground(new java.awt.Color(255, 255, 255));
        lbRazaoSocial.setLabelFor(txtRazaoSocial);
        lbRazaoSocial.setText("Razão Social  (Obrigatório)");

        lbSegmento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbSegmento.setForeground(new java.awt.Color(255, 255, 255));
        lbSegmento.setLabelFor(txtSegmento);
        lbSegmento.setText("Segmento");

        try {
            txtDataFundacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        painelLogo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Logo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        painelLogo.setOpaque(false);

        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ios7-contact-outline.png"))); // NOI18N
        lbLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout painelLogoLayout = new javax.swing.GroupLayout(painelLogo);
        painelLogo.setLayout(painelLogoLayout);
        painelLogoLayout.setHorizontalGroup(
            painelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        painelLogoLayout.setVerticalGroup(
            painelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lbIE.setForeground(new java.awt.Color(255, 255, 255));
        lbIE.setText("I.E (Obrigatório)");

        lbCpfCnpj.setForeground(new java.awt.Color(255, 255, 255));
        lbCpfCnpj.setText("CPF/CNPJ (Obrigatório)");

        lbSite.setForeground(new java.awt.Color(255, 255, 255));
        lbSite.setText("Site");

        javax.swing.GroupLayout painelDadosPessoaisFornecedorLayout = new javax.swing.GroupLayout(painelDadosPessoaisFornecedor);
        painelDadosPessoaisFornecedor.setLayout(painelDadosPessoaisFornecedorLayout);
        painelDadosPessoaisFornecedorLayout.setHorizontalGroup(
            painelDadosPessoaisFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosPessoaisFornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosPessoaisFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painelDadosPessoaisFornecedorLayout.createSequentialGroup()
                        .addGroup(painelDadosPessoaisFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNomeFantasia)
                            .addComponent(txtNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painelTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(painelDadosPessoaisFornecedorLayout.createSequentialGroup()
                        .addGroup(painelDadosPessoaisFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbIE)
                            .addComponent(txtIE, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelDadosPessoaisFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelDadosPessoaisFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbSite)
                            .addComponent(txtSite)))
                    .addGroup(painelDadosPessoaisFornecedorLayout.createSequentialGroup()
                        .addGroup(painelDadosPessoaisFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelDadosPessoaisFornecedorLayout.createSequentialGroup()
                                .addComponent(lbRazaoSocial)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtRazaoSocial))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelDadosPessoaisFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDataFundacao, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDataFundacao, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelDadosPessoaisFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSegmento, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbSegmento))))
                .addGap(71, 71, 71)
                .addComponent(painelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        painelDadosPessoaisFornecedorLayout.setVerticalGroup(
            painelDadosPessoaisFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosPessoaisFornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosPessoaisFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelDadosPessoaisFornecedorLayout.createSequentialGroup()
                        .addGroup(painelDadosPessoaisFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(painelDadosPessoaisFornecedorLayout.createSequentialGroup()
                                .addGroup(painelDadosPessoaisFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(painelTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(painelDadosPessoaisFornecedorLayout.createSequentialGroup()
                                        .addComponent(lbNomeFantasia)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbRazaoSocial)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelDadosPessoaisFornecedorLayout.createSequentialGroup()
                                .addGroup(painelDadosPessoaisFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbDataFundacao)
                                    .addComponent(lbSegmento))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(painelDadosPessoaisFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtDataFundacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSegmento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(painelDadosPessoaisFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelDadosPessoaisFornecedorLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(painelDadosPessoaisFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painelDadosPessoaisFornecedorLayout.createSequentialGroup()
                                        .addComponent(lbCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(painelDadosPessoaisFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtIE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(lbIE)))
                            .addGroup(painelDadosPessoaisFornecedorLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(txtSite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelDadosPessoaisFornecedorLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(lbSite, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        painelEnderecoProfessor.setBackground(new java.awt.Color(102, 102, 102));
        painelEnderecoProfessor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Endereço", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        painelEnderecoProfessor.setOpaque(false);

        lbEndereco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbEndereco.setForeground(new java.awt.Color(255, 255, 255));
        lbEndereco.setLabelFor(txtEndereco);
        lbEndereco.setText("Endereço");

        lbComplementoEndereco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbComplementoEndereco.setForeground(new java.awt.Color(255, 255, 255));
        lbComplementoEndereco.setLabelFor(txtComplementoEndereco);
        lbComplementoEndereco.setText("Complemento do Endereço");

        lbCidade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbCidade.setForeground(new java.awt.Color(255, 255, 255));
        lbCidade.setText("Cidade");

        jcbUfResidencia.setModel(new javax.swing.DefaultComboBoxModel<>(Estados.values()));
        jcbUfResidencia.setSelectedItem(Estados.PA);

        lbUfResidencia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbUfResidencia.setForeground(new java.awt.Color(255, 255, 255));
        lbUfResidencia.setText("UF");

        try {
            txtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lbCep.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbCep.setForeground(new java.awt.Color(255, 255, 255));
        lbCep.setText("CEP");

        lbTelefone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbTelefone.setForeground(new java.awt.Color(255, 255, 255));
        lbTelefone.setText("Telefone");

        lbCelular.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbCelular.setForeground(new java.awt.Color(255, 255, 255));
        lbCelular.setText("Celular");

        lbEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbEmail.setForeground(new java.awt.Color(255, 255, 255));
        lbEmail.setText("Email (Obrigatório)");

        try {
            txtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lbBairro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbBairro.setForeground(new java.awt.Color(255, 255, 255));
        lbBairro.setLabelFor(txtBairro);
        lbBairro.setText("Bairro");

        javax.swing.GroupLayout painelEnderecoProfessorLayout = new javax.swing.GroupLayout(painelEnderecoProfessor);
        painelEnderecoProfessor.setLayout(painelEnderecoProfessorLayout);
        painelEnderecoProfessorLayout.setHorizontalGroup(
            painelEnderecoProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEnderecoProfessorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelEnderecoProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelEnderecoProfessorLayout.createSequentialGroup()
                        .addGroup(painelEnderecoProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCidade)
                            .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelEnderecoProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbUfResidencia)
                            .addComponent(jcbUfResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelEnderecoProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCep)
                            .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelEnderecoProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTelefone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelEnderecoProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCelular)
                            .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelEnderecoProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail)
                            .addGroup(painelEnderecoProfessorLayout.createSequentialGroup()
                                .addComponent(lbEmail)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(painelEnderecoProfessorLayout.createSequentialGroup()
                        .addGroup(painelEnderecoProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbEndereco)
                            .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelEnderecoProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtComplementoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbComplementoEndereco))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelEnderecoProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelEnderecoProfessorLayout.createSequentialGroup()
                                .addComponent(lbBairro)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtBairro))))
                .addContainerGap())
        );

        painelEnderecoProfessorLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtCelular, txtTelefone});

        painelEnderecoProfessorLayout.setVerticalGroup(
            painelEnderecoProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEnderecoProfessorLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(painelEnderecoProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEndereco)
                    .addComponent(lbComplementoEndereco)
                    .addComponent(lbBairro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelEnderecoProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtComplementoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelEnderecoProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCidade)
                    .addComponent(lbUfResidencia)
                    .addComponent(lbCep)
                    .addComponent(lbTelefone)
                    .addComponent(lbCelular)
                    .addComponent(lbEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelEnderecoProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbUfResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCancelar.setText("Cancelar");

        btnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/checkmark-round.png"))); // NOI18N
        btnConfirmar.setText("Confirmar");
        btnConfirmar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnConfirmar.setIconTextGap(20);

        javax.swing.GroupLayout painelDadosDoFornecedorLayout = new javax.swing.GroupLayout(painelDadosDoFornecedor);
        painelDadosDoFornecedor.setLayout(painelDadosDoFornecedorLayout);
        painelDadosDoFornecedorLayout.setHorizontalGroup(
            painelDadosDoFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosDoFornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosDoFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelEnderecoProfessor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelDadosPessoaisFornecedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDadosDoFornecedorLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        painelDadosDoFornecedorLayout.setVerticalGroup(
            painelDadosDoFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosDoFornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelDadosPessoaisFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelEnderecoProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(painelDadosDoFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jtPainelCadastro.addTab("Informações do(a) Fornecedor(a)", painelDadosDoFornecedor);

        jDesktopPane1.setLayer(txtNomeDesabilitado, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lbNomeDesabilitado, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtMatricula, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lbMatricula, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jtPainelCadastro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtPainelCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbMatricula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbNomeDesabilitado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeDesabilitado, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeDesabilitado, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNomeDesabilitado)
                    .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMatricula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtPainelCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * 
     * @param fornecedor dados do fornecedor
     */
    public void editarFornecedor(Fornecedor fornecedor) {
        this.lbLogo.setIcon(new ImageIcon(Arquivo.DIR_FOTOS.concat(fornecedor.getFoto())));
        this.lbLogo.setName(fornecedor.getFoto());
        
        this.txtMatricula.setText(PessoaBO.getCadastro(Integer.parseInt(fornecedor.getMatricula())));
        this.txtNomeDesabilitado.setText(fornecedor.getNomeFantasia());
        
        this.txtNomeFantasia.setText(fornecedor.getNomeFantasia());
        this.txtRazaoSocial.setText(fornecedor.getRazaoSocial());
        this.txtSegmento.setText(fornecedor.getSegmento());
        this.txtIE.setText(fornecedor.getInscricaoEstadual());
        this.txtCpfCnpj.setText(fornecedor.getCnpj());
        this.txtSite.setText(fornecedor.getSite());
        this.rbPessoaFisica.setSelected(fornecedor.getTipo().equals("Pessoa Física"));
        this.rbPessoaJuridica.setSelected(fornecedor.getTipo().equals("Pessoa Jurídica"));
        this.txtDataFundacao.setText(fornecedor.getDataFundacao());

        this.txtTelefone.setText(fornecedor.getTelefone());
        this.txtCelular.setText(fornecedor.getCelular());
        this.txtEmail.setText(fornecedor.getEmail());

        this.txtEndereco.setText(fornecedor.getEndereco());
        this.txtComplementoEndereco.setText(fornecedor.getComplemento());
        this.txtBairro.setText(fornecedor.getBairro());
        this.txtCidade.setText(fornecedor.getCidade());
        this.jcbUfResidencia.setSelectedItem(fornecedor.getUf());
        this.txtCep.setText(fornecedor.getCep());
    }
    
    public JButton getBtnCancelarFornecedor() {
        return btnCancelar;
    }
    
    public JButton getBtnConfirmar() {
        return btnConfirmar;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }
    
    public JTabbedPane getJtPainelCadastro() {
        return jtPainelCadastro;
    }

    public JRadioButton getRbPessoaFisica() {
        return rbPessoaFisica;
    }

    public JRadioButton getRbPessoaJuridica() {
        return rbPessoaJuridica;
    }

    public JTextField getTxtBairro() {
        return txtBairro;
    }

    public JFormattedTextField getTxtCelular() {
        return txtCelular;
    }

    public JFormattedTextField getTxtCep() {
        return txtCep;
    }

    public JTextField getTxtCidade() {
        return txtCidade;
    }

    public JTextField getTxtComplementoEndereco() {
        return txtComplementoEndereco;
    }

    public JTextField getTxtCpfCnpj() {
        return txtCpfCnpj;
    }

    public JFormattedTextField getTxtDataFundacao() {
        return txtDataFundacao;
    }

    public JTextField getTxtEmail() {
        return txtEmail;
    }

    public JTextField getTxtEndereco() {
        return txtEndereco;
    }

    public JTextField getTxtIE() {
        return txtIE;
    }

    public JTextField getTxtMatricula() {
        return txtMatricula;
    }

    public JTextField getTxtNomeFantasia() {
        return txtNomeFantasia;
    }

    public JTextField getTxtSegmento() {
        return txtSegmento;
    }

    public JTextField getTxtSite() {
        return txtSite;
    }

    public JFormattedTextField getTxtTelefone() {
        return txtTelefone;
    }

    public JComboBox<Estados> getJcbUfResidencia() {
        return jcbUfResidencia;
    }

    public JLabel getLbLogo() {
        return lbLogo;
    }

    public JTextField getTxtNomeDesabilitado() {
        return txtNomeDesabilitado;
    }

    public JTextField getTxtRazaoSocial() {
        return txtRazaoSocial;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.ButtonGroup grupoTipo;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JComboBox<Estados> jcbUfResidencia;
    private javax.swing.JTabbedPane jtPainelCadastro;
    private javax.swing.JLabel lbBairro;
    private javax.swing.JLabel lbCelular;
    private javax.swing.JLabel lbCep;
    private javax.swing.JLabel lbCidade;
    private javax.swing.JLabel lbComplementoEndereco;
    private javax.swing.JLabel lbCpfCnpj;
    private javax.swing.JLabel lbDataFundacao;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbEndereco;
    private javax.swing.JLabel lbIE;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbMatricula;
    private javax.swing.JLabel lbNomeDesabilitado;
    private javax.swing.JLabel lbNomeFantasia;
    private javax.swing.JLabel lbRazaoSocial;
    private javax.swing.JLabel lbSegmento;
    private javax.swing.JLabel lbSite;
    private javax.swing.JLabel lbTelefone;
    private javax.swing.JLabel lbUfResidencia;
    private javax.swing.JPanel painelDadosDoFornecedor;
    private javax.swing.JPanel painelDadosPessoaisFornecedor;
    private javax.swing.JPanel painelEnderecoProfessor;
    private javax.swing.JPanel painelLogo;
    private javax.swing.JPanel painelTipo;
    private javax.swing.JRadioButton rbPessoaFisica;
    private javax.swing.JRadioButton rbPessoaJuridica;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JFormattedTextField txtCelular;
    private javax.swing.JFormattedTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtComplementoEndereco;
    private javax.swing.JTextField txtCpfCnpj;
    private javax.swing.JFormattedTextField txtDataFundacao;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtIE;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNomeDesabilitado;
    private javax.swing.JTextField txtNomeFantasia;
    private javax.swing.JTextField txtRazaoSocial;
    private javax.swing.JTextField txtSegmento;
    private javax.swing.JTextField txtSite;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables

    private final int returnStatus = RET_CANCEL;
}
