/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.siseduc.view;

import br.com.siseduc.Siseduc;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.JToolBar;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juan Soares
 */
public class TelaPesquisaFornecedor extends javax.swing.JDialog {

    /**
    * 
    */
   private static final long serialVersionUID = -4806189881077039914L;
   /**
    * A return status code - returned if Cancel button has been pressed
    */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;
    /**
     * 
     */
    private DefaultTableModel model;

    /**
     * Creates new form TelaCadastroPesquisaAluno
     * @param parent super classe
     * @param modal informa se a janela é modal
     */
    public TelaPesquisaFornecedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        barraDeFerramentas = new javax.swing.JToolBar();
        btnNovoFornecedor = new javax.swing.JButton();
        btnEditarFornecedor = new javax.swing.JButton();
        btnExcluirFornecedor = new javax.swing.JButton();
        btnRelatorios = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jcbOrdenar = new javax.swing.JComboBox<>();
        txtPesquisar = new javax.swing.JTextField();
        lbOrdenar = new javax.swing.JLabel();
        lbPesquisar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaListarFornecedor = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle(Siseduc.TITULO);
        setMinimumSize(new java.awt.Dimension(871, 488));

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 204));

        barraDeFerramentas.setBorder(null);
        barraDeFerramentas.setFloatable(false);
        barraDeFerramentas.setRollover(true);

        btnNovoFornecedor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnNovoFornecedor.setForeground(new java.awt.Color(255, 255, 255));
        btnNovoFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrow-swap-big.png"))); // NOI18N
        btnNovoFornecedor.setText("Novo");
        btnNovoFornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNovoFornecedor.setFocusable(false);
        btnNovoFornecedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNovoFornecedor.setPreferredSize(new java.awt.Dimension(90, 90));
        btnNovoFornecedor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barraDeFerramentas.add(btnNovoFornecedor);

        btnEditarFornecedor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEditarFornecedor.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/compose.png"))); // NOI18N
        btnEditarFornecedor.setText("Editar");
        btnEditarFornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditarFornecedor.setFocusable(false);
        btnEditarFornecedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditarFornecedor.setPreferredSize(new java.awt.Dimension(90, 90));
        btnEditarFornecedor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barraDeFerramentas.add(btnEditarFornecedor);

        btnExcluirFornecedor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnExcluirFornecedor.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluirFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ios7-close-outline.png"))); // NOI18N
        btnExcluirFornecedor.setText("Excluir");
        btnExcluirFornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluirFornecedor.setFocusable(false);
        btnExcluirFornecedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcluirFornecedor.setPreferredSize(new java.awt.Dimension(90, 90));
        btnExcluirFornecedor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barraDeFerramentas.add(btnExcluirFornecedor);

        btnRelatorios.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRelatorios.setForeground(new java.awt.Color(255, 255, 255));
        btnRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ios7-paper-outline.png"))); // NOI18N
        btnRelatorios.setText("Relatórios");
        btnRelatorios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRelatorios.setFocusable(false);
        btnRelatorios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRelatorios.setPreferredSize(new java.awt.Dimension(90, 90));
        btnRelatorios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barraDeFerramentas.add(btnRelatorios);

        btnSair.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 255, 255));
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/log-out.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSair.setFocusable(false);
        btnSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSair.setPreferredSize(new java.awt.Dimension(90, 90));
        btnSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barraDeFerramentas.add(btnSair);

        jcbOrdenar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cadastro", "Nome Fantasia", "Segmento", "Cidade", "Estado" }));

        lbOrdenar.setForeground(new java.awt.Color(255, 255, 255));
        lbOrdenar.setText("Ordenar por:");

        lbPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        lbPesquisar.setText("Pesquisa por nome");

        tabelaListarFornecedor.setModel(model = new DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cadastro", "Nome Fantasia", "Segmento", "Telefone", "Email", "Site"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaListarFornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabelaListarFornecedor.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabelaListarFornecedor);

        jDesktopPane1.setLayer(barraDeFerramentas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jcbOrdenar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtPesquisar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lbOrdenar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lbPesquisar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(barraDeFerramentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbOrdenar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbOrdenar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(lbPesquisar)
                                .addGap(0, 191, Short.MAX_VALUE))
                            .addComponent(txtPesquisar))))
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(barraDeFerramentas, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbOrdenar)
                            .addComponent(lbPesquisar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbOrdenar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public DefaultTableModel getModel() {
        return model;
    }
    
    public JButton getBtnEditarFornecedor() {
        return btnEditarFornecedor;
    }

    public JButton getBtnExcluirFornecedor() {
        return btnExcluirFornecedor;
    }

    public JButton getBtnNovoFornecedor() {
        return btnNovoFornecedor;
    }

    public JButton getBtnRelatorios() {
        return btnRelatorios;
    }

    public JButton getBtnSair() {
        return btnSair;
    }

    public JComboBox<String> getJcbOrdenar() {
        return jcbOrdenar;
    }

    public JTable getTabelaListarFornecedor() {
        return tabelaListarFornecedor;
    }

    public JTextField getTxtPesquisar() {
        return txtPesquisar;
    }

    public JToolBar getBarraDeFerramentas() {
        return barraDeFerramentas;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar barraDeFerramentas;
    private javax.swing.JButton btnEditarFornecedor;
    private javax.swing.JButton btnExcluirFornecedor;
    private javax.swing.JButton btnNovoFornecedor;
    private javax.swing.JButton btnRelatorios;
    private javax.swing.JButton btnSair;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbOrdenar;
    private javax.swing.JLabel lbOrdenar;
    private javax.swing.JLabel lbPesquisar;
    private javax.swing.JTable tabelaListarFornecedor;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables

    private final int returnStatus = RET_CANCEL;
}