/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.siseduc.view;


import br.com.siseduc.Siseduc;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.JToolBar;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juan Soares
 */
public class TelaPesquisaAluno extends javax.swing.JDialog {

    /**
    * 
    */
   private static final long serialVersionUID = 4848102157511887812L;
   /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;
    
    /**
     * 
     */
    private final DefaultTableModel tabelaPadrao = new DefaultTableModel();

    /**
     * Creates new form TelaCadastroPesquisaAluno
     * @param parent super classe
     * @param modal informa se a janela é modal
     */
    public TelaPesquisaAluno(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuFlutuante = new javax.swing.JPopupMenu();
        jmiEditarAluno = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmiGerarHistorico = new javax.swing.JMenuItem();
        jmiGerarBoletim = new javax.swing.JMenuItem();
        jmiGerarDeclaracao = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        barraDeFerramentas = new javax.swing.JToolBar();
        btnNovoAluno = new javax.swing.JButton();
        btnEditarAluno = new javax.swing.JButton();
        btnExcluirAluno = new javax.swing.JButton();
        btnRelatorios = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jcbOrdenar = new javax.swing.JComboBox<>();
        txtPesquisar = new javax.swing.JTextField();
        lbOrdenar = new javax.swing.JLabel();
        lbPesquisar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaListarAluno = new javax.swing.JTable() {
            public boolean isCellEditable(int col, int row) {
                return false;
            }
        };
        btnProxima = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        lbInicio = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbTotalPaginas = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbTotal = new javax.swing.JLabel();

        menuFlutuante.setOpaque(false);

        jmiEditarAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/compose-mini.png"))); // NOI18N
        jmiEditarAluno.setText("Editar Aluno");
        menuFlutuante.add(jmiEditarAluno);
        menuFlutuante.add(jSeparator1);

        jmiGerarHistorico.setText("Gerar Histórico");
        menuFlutuante.add(jmiGerarHistorico);

        jmiGerarBoletim.setText("Gerar Boletim");
        menuFlutuante.add(jmiGerarBoletim);

        jmiGerarDeclaracao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jmiGerarDeclaracao.setText("Gerar Declaração");
        menuFlutuante.add(jmiGerarDeclaracao);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle(Siseduc.TITULO);
        setMinimumSize(new java.awt.Dimension(871, 488));

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 204));

        barraDeFerramentas.setBorder(null);
        barraDeFerramentas.setFloatable(false);
        barraDeFerramentas.setRollover(true);

        btnNovoAluno.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnNovoAluno.setForeground(new java.awt.Color(255, 255, 255));
        btnNovoAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/person-add.png"))); // NOI18N
        btnNovoAluno.setMnemonic('N');
        btnNovoAluno.setText("Novo Aluno");
        btnNovoAluno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNovoAluno.setFocusable(false);
        btnNovoAluno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNovoAluno.setPreferredSize(new java.awt.Dimension(90, 90));
        btnNovoAluno.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barraDeFerramentas.add(btnNovoAluno);

        btnEditarAluno.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEditarAluno.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/compose.png"))); // NOI18N
        btnEditarAluno.setMnemonic('E');
        btnEditarAluno.setText("Editar Aluno");
        btnEditarAluno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditarAluno.setFocusable(false);
        btnEditarAluno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditarAluno.setPreferredSize(new java.awt.Dimension(90, 90));
        btnEditarAluno.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barraDeFerramentas.add(btnEditarAluno);

        btnExcluirAluno.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnExcluirAluno.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluirAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ios7-close-outline.png"))); // NOI18N
        btnExcluirAluno.setMnemonic('X');
        btnExcluirAluno.setText("Excluir Aluno");
        btnExcluirAluno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluirAluno.setFocusable(false);
        btnExcluirAluno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcluirAluno.setPreferredSize(new java.awt.Dimension(90, 90));
        btnExcluirAluno.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barraDeFerramentas.add(btnExcluirAluno);

        btnRelatorios.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRelatorios.setForeground(new java.awt.Color(255, 255, 255));
        btnRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ios7-paper-outline.png"))); // NOI18N
        btnRelatorios.setMnemonic('R');
        btnRelatorios.setText("Relatórios");
        btnRelatorios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRelatorios.setFocusable(false);
        btnRelatorios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRelatorios.setPreferredSize(new java.awt.Dimension(90, 90));
        btnRelatorios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatoriosActionPerformed(evt);
            }
        });
        barraDeFerramentas.add(btnRelatorios);

        btnSair.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 255, 255));
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/log-out.png"))); // NOI18N
        btnSair.setMnemonic('S');
        btnSair.setText("Sair");
        btnSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSair.setFocusable(false);
        btnSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSair.setPreferredSize(new java.awt.Dimension(90, 90));
        btnSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barraDeFerramentas.add(btnSair);

        jcbOrdenar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "Data Cadastro", "Matricula", "Data Nascimento", "Naturalidade" }));

        lbOrdenar.setForeground(new java.awt.Color(255, 255, 255));
        lbOrdenar.setText("Ordenar por:");

        lbPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        lbPesquisar.setText("Pesquisa por nome");

        tabelaListarAluno.setModel(tabelaPadrao);
        tabelaListarAluno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabelaListarAluno.getTableHeader().setReorderingAllowed(false);
        criarTabela();
        jScrollPane1.setViewportView(tabelaListarAluno);

        btnProxima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ios7-arrow-forward-mini.png"))); // NOI18N
        btnProxima.setToolTipText("Avançar uma página");
        btnProxima.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProxima.setMinimumSize(new java.awt.Dimension(0, 0));
        btnProxima.setPreferredSize(new java.awt.Dimension(40, 35));

        btnAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ios7-arrow-back-mini.PNG"))); // NOI18N
        btnAnterior.setToolTipText("Voltar uma página");
        btnAnterior.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAnterior.setEnabled(false);
        btnAnterior.setMinimumSize(new java.awt.Dimension(0, 0));
        btnAnterior.setPreferredSize(new java.awt.Dimension(40, 35));

        lbInicio.setForeground(new java.awt.Color(255, 255, 255));
        lbInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbInicio.setText("0");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("de");

        lbTotalPaginas.setForeground(new java.awt.Color(255, 255, 255));
        lbTotalPaginas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTotalPaginas.setText("0");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("-  total de registros");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mostrando página");

        lbTotal.setForeground(new java.awt.Color(255, 255, 255));
        lbTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTotal.setText("0");

        jDesktopPane1.setLayer(barraDeFerramentas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jcbOrdenar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtPesquisar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lbOrdenar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lbPesquisar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnProxima, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnAnterior, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lbInicio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lbTotalPaginas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lbTotal, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(barraDeFerramentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbOrdenar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbOrdenar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbPesquisar)
                                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnProxima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbTotalPaginas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 904, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(barraDeFerramentas, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbOrdenar)
                            .addComponent(lbPesquisar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbOrdenar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAnterior, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbTotalPaginas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addComponent(lbTotal))
                            .addComponent(btnProxima, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatoriosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRelatoriosActionPerformed

    public void criarTabela() {
        tabelaPadrao.addColumn("Matrícula");
        tabelaPadrao.addColumn("Nome");
        tabelaPadrao.addColumn("Telefone");
        tabelaPadrao.addColumn("Celular");
        tabelaPadrao.addColumn("Email");
        
        tabelaListarAluno.getColumnModel().getColumn(0).setPreferredWidth(50);
        
    }

    public JButton getBtnEditarAluno() {
        return btnEditarAluno;
    }

    public JButton getBtnExcluirAluno() {
        return btnExcluirAluno;
    }

    public JButton getBtnNovoAluno() {
        return btnNovoAluno;
    }

    public JButton getBtnRelatorios() {
        return btnRelatorios;
    }

    public JButton getBtnSair() {
        return btnSair;
    }

    public JComboBox<String> getJcbOrdenar() {
        return jcbOrdenar;
    }

    public JTable getTabelaListarAluno() {
        return tabelaListarAluno;
    }

    public JTextField getTxtPesquisar() {
        return txtPesquisar;
    }

    public DefaultTableModel getTabelaPadrao() {
        return tabelaPadrao;
    }

    public JMenuItem getJmiEditarAluno() {
        return jmiEditarAluno;
    }

    public JPopupMenu getMenuFlutuante() {
        return menuFlutuante;
    }

    public JMenuItem getJmiGerarDeclaracao() {
        return jmiGerarDeclaracao;
    }

    public JMenuItem getJmiGerarHistorico() {
        return jmiGerarHistorico;
    }

    public JMenuItem getJmiGerarBoletim() {
        return jmiGerarBoletim;
    }

    public JToolBar getBarraDeFerramentas() {
        return barraDeFerramentas;
    }

    public JLabel getLbInicio() {
        return lbInicio;
    }

    public JLabel getLbTotalPaginas() {
        return lbTotalPaginas;
    }

    public JLabel getLbTotal() {
        return lbTotal;
    }

    public JButton getBtnAnterior() {
        return btnAnterior;
    }

    public JButton getBtnProxima() {
        return btnProxima;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar barraDeFerramentas;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnEditarAluno;
    private javax.swing.JButton btnExcluirAluno;
    private javax.swing.JButton btnNovoAluno;
    private javax.swing.JButton btnProxima;
    private javax.swing.JButton btnRelatorios;
    private javax.swing.JButton btnSair;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JComboBox<String> jcbOrdenar;
    private javax.swing.JMenuItem jmiEditarAluno;
    private javax.swing.JMenuItem jmiGerarBoletim;
    private javax.swing.JMenuItem jmiGerarDeclaracao;
    private javax.swing.JMenuItem jmiGerarHistorico;
    private javax.swing.JLabel lbInicio;
    private javax.swing.JLabel lbOrdenar;
    private javax.swing.JLabel lbPesquisar;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JLabel lbTotalPaginas;
    private javax.swing.JPopupMenu menuFlutuante;
    private javax.swing.JTable tabelaListarAluno;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables

    private final int returnStatus = RET_CANCEL;
}
