/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.siseduc.view;

import br.com.siseduc.Siseduc;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JList;
import javax.swing.JRadioButton;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;

/**
 *
 * @author Juan Soares
 */
public class TelaCadastroTurma extends javax.swing.JDialog {

    /**
     *
     */
    private static final long serialVersionUID = 4492139719514535896L;
    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;

    /**
     * Creates new form TelaCadastroAluno
     *
     * @param parent super classe
     * @param modal informa se a janela é modal
     */
    public TelaCadastroTurma(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoTurmaAtiva = new javax.swing.ButtonGroup();
        grupoCancelada = new javax.swing.ButtonGroup();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        txtTurma = new javax.swing.JTextField();
        lbMatricula = new javax.swing.JLabel();
        jtPainelCadastroAluno = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        painelDadosTurma = new javax.swing.JPanel();
        jcbModalidade = new javax.swing.JComboBox<>();
        lbModalidade = new javax.swing.JLabel();
        jcbSerie = new javax.swing.JComboBox<>();
        lbSerie = new javax.swing.JLabel();
        txtDescricaoSerie = new javax.swing.JTextField();
        lbDescricaoSerie = new javax.swing.JLabel();
        jcbTurno = new javax.swing.JComboBox<>();
        lbTurno = new javax.swing.JLabel();
        txtDescricaoTurma = new javax.swing.JTextField();
        lbDescricaoTurma = new javax.swing.JLabel();
        painelCancelada = new javax.swing.JPanel();
        rbCanceladaSim = new javax.swing.JRadioButton();
        rbCanceladaNao = new javax.swing.JRadioButton();
        lbDataCancelamento = new javax.swing.JLabel();
        txtDataCancelamento = new javax.swing.JFormattedTextField();
        txtDataInativarTurma = new javax.swing.JFormattedTextField();
        lbDataInativarTurma = new javax.swing.JLabel();
        painelAtiva1 = new javax.swing.JPanel();
        rbAtivaSim = new javax.swing.JRadioButton();
        rbAtivaNao = new javax.swing.JRadioButton();
        lbDataMatricula = new javax.swing.JLabel();
        txtDataMatricula = new javax.swing.JFormattedTextField();
        txtDataModificacao = new javax.swing.JFormattedTextField();
        lbDataModificacao = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlGrade = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txtPesquisaProfessor = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlProfessor = new javax.swing.JList<>();
        btnInserirProfessor = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jlListaProfessores = new javax.swing.JList<>();
        btnRemoverProfessor = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle(Siseduc.TITULO);
        setIconImage(new ImageIcon(getClass().getResource("/images/icone.png")).getImage());
        setResizable(false);

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 204));

        txtTurma.setEditable(false);
        txtTurma.setBackground(new java.awt.Color(204, 204, 204));
        txtTurma.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbMatricula.setForeground(new java.awt.Color(255, 255, 255));
        lbMatricula.setText("Turma");

        jtPainelCadastroAluno.setBackground(new java.awt.Color(204, 204, 204));
        jtPainelCadastroAluno.setPreferredSize(new java.awt.Dimension(914, 300));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setOpaque(false);

        painelDadosTurma.setBackground(new java.awt.Color(102, 102, 102));
        painelDadosTurma.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Turma", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        painelDadosTurma.setOpaque(false);

        jcbModalidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha a Modalidade", "Ensino Fundamental", "Ensino Médio", "EJA" }));

        lbModalidade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbModalidade.setForeground(new java.awt.Color(255, 255, 255));
        lbModalidade.setText("Modalidade");

        jcbSerie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha a Série" }));

        lbSerie.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbSerie.setForeground(new java.awt.Color(255, 255, 255));
        lbSerie.setText("Série");

        txtDescricaoSerie.setEditable(false);

        lbDescricaoSerie.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbDescricaoSerie.setForeground(new java.awt.Color(255, 255, 255));
        lbDescricaoSerie.setText("Descrição da Série");

        jcbTurno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha o Turno", "Matutino", "Vespertino", "Noturno" }));

        lbTurno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbTurno.setForeground(new java.awt.Color(255, 255, 255));
        lbTurno.setText("Turno");

        lbDescricaoTurma.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbDescricaoTurma.setForeground(new java.awt.Color(255, 255, 255));
        lbDescricaoTurma.setText("Descrição da Turma");

        painelCancelada.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cancelada", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        painelCancelada.setOpaque(false);

        grupoCancelada.add(rbCanceladaSim);
        rbCanceladaSim.setForeground(new java.awt.Color(255, 255, 255));
        rbCanceladaSim.setText("Sim");
        rbCanceladaSim.setOpaque(false);

        grupoCancelada.add(rbCanceladaNao);
        rbCanceladaNao.setForeground(new java.awt.Color(255, 255, 255));
        rbCanceladaNao.setSelected(true);
        rbCanceladaNao.setText("Não");
        rbCanceladaNao.setOpaque(false);

        javax.swing.GroupLayout painelCanceladaLayout = new javax.swing.GroupLayout(painelCancelada);
        painelCancelada.setLayout(painelCanceladaLayout);
        painelCanceladaLayout.setHorizontalGroup(
            painelCanceladaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCanceladaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbCanceladaSim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbCanceladaNao)
                .addGap(16, 16, 16))
        );
        painelCanceladaLayout.setVerticalGroup(
            painelCanceladaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCanceladaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(painelCanceladaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCanceladaSim)
                    .addComponent(rbCanceladaNao)))
        );

        lbDataCancelamento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbDataCancelamento.setForeground(new java.awt.Color(255, 255, 255));
        lbDataCancelamento.setText("Cancelada em");

        txtDataCancelamento.setEditable(false);
        try {
            txtDataCancelamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        txtDataInativarTurma.setEditable(false);
        try {
            txtDataInativarTurma.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lbDataInativarTurma.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbDataInativarTurma.setForeground(new java.awt.Color(255, 255, 255));
        lbDataInativarTurma.setText("Ativada em");

        painelAtiva1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ativa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        painelAtiva1.setOpaque(false);

        grupoTurmaAtiva.add(rbAtivaSim);
        rbAtivaSim.setForeground(new java.awt.Color(255, 255, 255));
        rbAtivaSim.setText("Sim");
        rbAtivaSim.setOpaque(false);

        grupoTurmaAtiva.add(rbAtivaNao);
        rbAtivaNao.setForeground(new java.awt.Color(255, 255, 255));
        rbAtivaNao.setSelected(true);
        rbAtivaNao.setText("Não");
        rbAtivaNao.setOpaque(false);

        javax.swing.GroupLayout painelAtiva1Layout = new javax.swing.GroupLayout(painelAtiva1);
        painelAtiva1.setLayout(painelAtiva1Layout);
        painelAtiva1Layout.setHorizontalGroup(
            painelAtiva1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAtiva1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbAtivaSim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbAtivaNao)
                .addGap(16, 16, 16))
        );
        painelAtiva1Layout.setVerticalGroup(
            painelAtiva1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelAtiva1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(painelAtiva1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbAtivaSim)
                    .addComponent(rbAtivaNao)))
        );

        lbDataMatricula.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbDataMatricula.setForeground(new java.awt.Color(255, 255, 255));
        lbDataMatricula.setText("Data Cadastro");

        txtDataMatricula.setEditable(false);
        try {
            txtDataMatricula.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataMatricula.setText(new SimpleDateFormat("dd/MM/yyyy").format(new Date()));

        txtDataModificacao.setEditable(false);
        try {
            txtDataModificacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataModificacao.setText(new SimpleDateFormat("dd/MM/yyyy").format(new Date()));

        lbDataModificacao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbDataModificacao.setForeground(new java.awt.Color(255, 255, 255));
        lbDataModificacao.setText("Modificada em");

        javax.swing.GroupLayout painelDadosTurmaLayout = new javax.swing.GroupLayout(painelDadosTurma);
        painelDadosTurma.setLayout(painelDadosTurmaLayout);
        painelDadosTurmaLayout.setHorizontalGroup(
            painelDadosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosTurmaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDadosTurmaLayout.createSequentialGroup()
                        .addGroup(painelDadosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbModalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbModalidade))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(painelDadosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelDadosTurmaLayout.createSequentialGroup()
                                .addComponent(lbSerie)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jcbSerie, 0, 138, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelDadosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDescricaoSerie)
                            .addComponent(txtDescricaoSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(painelDadosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTurno)
                            .addComponent(jcbTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelDadosTurmaLayout.createSequentialGroup()
                        .addComponent(painelAtiva1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(painelCancelada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painelDadosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDataCancelamento)
                            .addComponent(txtDataCancelamento, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painelDadosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDataInativarTurma)
                            .addComponent(txtDataInativarTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(painelDadosTurmaLayout.createSequentialGroup()
                        .addGroup(painelDadosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDescricaoTurma)
                            .addComponent(txtDescricaoTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelDadosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDataMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDataMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelDadosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelDadosTurmaLayout.createSequentialGroup()
                                .addComponent(lbDataModificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDadosTurmaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDataModificacao)))))
                .addContainerGap())
        );
        painelDadosTurmaLayout.setVerticalGroup(
            painelDadosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosTurmaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(painelDadosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbModalidade)
                    .addComponent(lbSerie)
                    .addComponent(lbDescricaoSerie)
                    .addComponent(lbTurno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDadosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcbModalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jcbSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDadosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcbTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDescricaoSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(painelDadosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painelDadosTurmaLayout.createSequentialGroup()
                        .addComponent(lbDescricaoTurma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescricaoTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelDadosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(painelDadosTurmaLayout.createSequentialGroup()
                            .addComponent(lbDataMatricula)
                            .addGap(26, 26, 26))
                        .addComponent(txtDataMatricula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelDadosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(painelDadosTurmaLayout.createSequentialGroup()
                            .addComponent(lbDataModificacao)
                            .addGap(27, 27, 27))
                        .addComponent(txtDataModificacao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(painelDadosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDadosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(painelCancelada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(painelAtiva1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelDadosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(painelDadosTurmaLayout.createSequentialGroup()
                            .addComponent(lbDataInativarTurma)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtDataInativarTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(painelDadosTurmaLayout.createSequentialGroup()
                            .addComponent(lbDataCancelamento)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtDataCancelamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelDadosTurma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelDadosTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        jtPainelCadastroAluno.addTab("Informações da Turma", jPanel1);

        jPanel2.setOpaque(false);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Grade Curricular - Base Nacional", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setFocusable(false);
        jPanel3.setMinimumSize(new java.awt.Dimension(303, 205));
        jPanel3.setOpaque(false);

        jlGrade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlGrade.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jlGrade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlGrade.setFocusable(false);
        jScrollPane1.setViewportView(jlGrade);

        jButton1.setText("Alterar Grade");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Adicionar Professor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel4.setMaximumSize(new java.awt.Dimension(353, 285));
        jPanel4.setMinimumSize(new java.awt.Dimension(353, 285));
        jPanel4.setOpaque(false);

        txtPesquisaProfessor.setMaximumSize(new java.awt.Dimension(191, 27));
        txtPesquisaProfessor.setMinimumSize(new java.awt.Dimension(191, 27));
        txtPesquisaProfessor.setPreferredSize(new java.awt.Dimension(191, 27));

        jlProfessor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlProfessor.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jlProfessor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlProfessor.setFocusable(false);
        jScrollPane2.setViewportView(jlProfessor);

        btnInserirProfessor.setText("Inserir Professor");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtPesquisaProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInserirProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInserirProfessor)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(txtPesquisaProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Relação de Professores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.setFocusable(false);
        jPanel5.setMaximumSize(new java.awt.Dimension(257, 194));
        jPanel5.setMinimumSize(new java.awt.Dimension(257, 194));
        jPanel5.setOpaque(false);

        jlListaProfessores.setFocusable(false);
        jScrollPane3.setViewportView(jlListaProfessores);

        btnRemoverProfessor.setText("Remover Professor");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnRemoverProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 89, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRemoverProfessor)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jtPainelCadastroAluno.addTab("Grade de professores", jPanel2);

        btnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/checkmark-round.png"))); // NOI18N
        btnConfirmar.setText("Confirmar");
        btnConfirmar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnConfirmar.setIconTextGap(10);

        btnCancelar.setText("Cancelar");

        jDesktopPane1.setLayer(txtTurma, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lbMatricula, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jtPainelCadastroAluno, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnConfirmar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnCancelar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(0, 799, Short.MAX_VALUE)
                                .addComponent(lbMatricula)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtPainelCadastroAluno, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMatricula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtPainelCadastroAluno, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public JButton getBtnConfirmar() {
        return btnConfirmar;
    }
    
    public JComboBox<String> getJcbModalidade() {
        return jcbModalidade;
    }

    public JComboBox<String> getJcbSerie() {
        return jcbSerie;
    }

    public JComboBox<String> getJcbTurno() {
        return jcbTurno;
    }

    public JTabbedPane getJtPainelCadastroAluno() {
        return jtPainelCadastroAluno;
    }

    public JRadioButton getRbAtivaNao() {
        return rbAtivaNao;
    }

    public JRadioButton getRbAtivaSim() {
        return rbAtivaSim;
    }

    public JRadioButton getRbCanceladaNao() {
        return rbCanceladaNao;
    }

    public JRadioButton getRbCanceladaSim() {
        return rbCanceladaSim;
    }

    public JFormattedTextField getTxtDataCancelamento() {
        return txtDataCancelamento;
    }

    public JFormattedTextField getTxtDataInativarTurma() {
        return txtDataInativarTurma;
    }

    public JFormattedTextField getTxtDataMatricula() {
        return txtDataMatricula;
    }

    public JFormattedTextField getTxtDataModificacao() {
        return txtDataModificacao;
    }

    public JTextField getTxtDescricaoSerie() {
        return txtDescricaoSerie;
    }

    public JTextField getTxtDescricaoTurma() {
        return txtDescricaoTurma;
    }

    public JTextField getTxtTurma() {
        return txtTurma;
    }

    public JList<String> getJlGrade() {
        return jlGrade;
    }

    public JButton getBtnInserirProfessor() {
        return btnInserirProfessor;
    }

    public JTextField getTxtPesquisaProfessor() {
        return txtPesquisaProfessor;
    }

    public JList<String> getJlProfessor() {
        return jlProfessor;
    }

    public JList<String> getJlListaProfessores() {
        return jlListaProfessores;
    }

    public JButton getBtnRemoverProfessor() {
        return btnRemoverProfessor;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnInserirProfessor;
    private javax.swing.JButton btnRemoverProfessor;
    private javax.swing.ButtonGroup grupoCancelada;
    private javax.swing.ButtonGroup grupoTurmaAtiva;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox<String> jcbModalidade;
    private javax.swing.JComboBox<String> jcbSerie;
    private javax.swing.JComboBox<String> jcbTurno;
    private javax.swing.JList<String> jlGrade;
    private javax.swing.JList<String> jlListaProfessores;
    private javax.swing.JList<String> jlProfessor;
    private javax.swing.JTabbedPane jtPainelCadastroAluno;
    private javax.swing.JLabel lbDataCancelamento;
    private javax.swing.JLabel lbDataInativarTurma;
    private javax.swing.JLabel lbDataMatricula;
    private javax.swing.JLabel lbDataModificacao;
    private javax.swing.JLabel lbDescricaoSerie;
    private javax.swing.JLabel lbDescricaoTurma;
    private javax.swing.JLabel lbMatricula;
    private javax.swing.JLabel lbModalidade;
    private javax.swing.JLabel lbSerie;
    private javax.swing.JLabel lbTurno;
    private javax.swing.JPanel painelAtiva1;
    private javax.swing.JPanel painelCancelada;
    private javax.swing.JPanel painelDadosTurma;
    private javax.swing.JRadioButton rbAtivaNao;
    private javax.swing.JRadioButton rbAtivaSim;
    private javax.swing.JRadioButton rbCanceladaNao;
    private javax.swing.JRadioButton rbCanceladaSim;
    private javax.swing.JFormattedTextField txtDataCancelamento;
    private javax.swing.JFormattedTextField txtDataInativarTurma;
    private javax.swing.JFormattedTextField txtDataMatricula;
    private javax.swing.JFormattedTextField txtDataModificacao;
    private javax.swing.JTextField txtDescricaoSerie;
    private javax.swing.JTextField txtDescricaoTurma;
    private javax.swing.JTextField txtPesquisaProfessor;
    private javax.swing.JTextField txtTurma;
    // End of variables declaration//GEN-END:variables

    private final int returnStatus = RET_CANCEL;
}
