/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.siseduc.view;

import br.com.siseduc.Siseduc;
import br.com.siseduc.model.dao.Arquivo;
import br.com.siseduc.model.vo.Estados;
import br.com.siseduc.model.vo.Usuario;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;
import javax.swing.JTextPane;

/**
 *
 * @author Juan Soares
 */
public class TelaCadastroFuncionario extends javax.swing.JDialog {

    /**
     *
     */
    private static final long serialVersionUID = 3156301263829921163L;
    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;

    /**
     *
     */
    private final TelaCadastroUsuario telaCadastroUsuario;

    /**
     * Creates new form TelaCadastroAluno
     *
     * @param parent super classe
     * @param modal informa se a janela é modal
     */
    public TelaCadastroFuncionario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.telaCadastroUsuario = new TelaCadastroUsuario(this.jtPainelCadastro, this);

    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoSexo = new javax.swing.ButtonGroup();
        grupoUsuario = new javax.swing.ButtonGroup();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        txtNomeDesabilitado = new javax.swing.JTextField();
        lbNomeDesabilitado = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        lbMatricula = new javax.swing.JLabel();
        jtPainelCadastro = new javax.swing.JTabbedPane();
        painelDadosDoFuncionario = new javax.swing.JPanel();
        painelDadosPessoaisFuncionario = new javax.swing.JPanel();
        txtNomeFuncionario = new javax.swing.JTextField();
        lbNomeFuncionario = new javax.swing.JLabel();
        painelSexo = new javax.swing.JPanel();
        rbSexoMasculino = new javax.swing.JRadioButton();
        rbSexoFeminino = new javax.swing.JRadioButton();
        lbDataNascimentoFuncionario = new javax.swing.JLabel();
        lbNacionalidadeFuncionario = new javax.swing.JLabel();
        txtNacionalidadeFuncionario = new javax.swing.JTextField();
        lbNaturalidadeFuncionario = new javax.swing.JLabel();
        txtNaturalidadeFuncionario = new javax.swing.JTextField();
        jcbUfNaturalidadeFuncionario = new javax.swing.JComboBox<>();
        lbUfNaturalidadeFuncionario = new javax.swing.JLabel();
        txtDataNascimentoFuncionario = new javax.swing.JFormattedTextField();
        painelFotoFuncionario = new javax.swing.JPanel();
        lbFoto = new javax.swing.JLabel();
        lbIdentidadeFuncionario = new javax.swing.JLabel();
        txtIdentidadeFuncionario = new javax.swing.JFormattedTextField();
        txtCpfFuncionario = new javax.swing.JFormattedTextField();
        lbCpfFuncionario = new javax.swing.JLabel();
        txtDataCadastroFuncionario = new javax.swing.JTextField();
        lbDataCadastroFuncionario = new javax.swing.JLabel();
        painelEnderecoFuncionario = new javax.swing.JPanel();
        txtEnderecoFuncionario = new javax.swing.JTextField();
        lbEnderecoFuncionario = new javax.swing.JLabel();
        txtComplementoEnderecoFuncionario = new javax.swing.JTextField();
        lbComplementoEnderecoFuncionario = new javax.swing.JLabel();
        txtCidadeFuncionario = new javax.swing.JTextField();
        lbCidadeFuncionario = new javax.swing.JLabel();
        jcbUfResidenciaFuncionario = new javax.swing.JComboBox<>();
        lbUfResidenciaFuncionario = new javax.swing.JLabel();
        txtCepFuncionario = new javax.swing.JFormattedTextField();
        txtTelefoneFuncionario = new javax.swing.JFormattedTextField();
        lbCepFuncionario = new javax.swing.JLabel();
        lbTelefoneFuncionario = new javax.swing.JLabel();
        lbCelularFuncionario = new javax.swing.JLabel();
        lbEmailFuncionario = new javax.swing.JLabel();
        txtCelularFuncionario = new javax.swing.JFormattedTextField();
        txtEmailFuncionario = new javax.swing.JTextField();
        txtBairroFuncionario = new javax.swing.JTextField();
        lbBairroFuncionario = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jcbCargoFuncao = new javax.swing.JComboBox<>();
        lbTitulo = new javax.swing.JLabel();
        lbCurso = new javax.swing.JLabel();
        lbInstituicao = new javax.swing.JLabel();
        jcbEscolaridade = new javax.swing.JComboBox<>();
        txtCargaHoraria = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricaoFuncao = new javax.swing.JTextPane();
        jPanel5 = new javax.swing.JPanel();
        rbUsuarioSim = new javax.swing.JRadioButton();
        rbUsuarioNao = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        txtNumeroCTPS = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtSerieCTPS = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDataEmissao = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNumeroPIS = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDependentes = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtConfirmar = new javax.swing.JTextPane();
        jPanel8 = new javax.swing.JPanel();
        btnConfirmar = new javax.swing.JButton();
        btnCorrigir = new javax.swing.JButton();
        btnProximoPasso = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle(Siseduc.TITULO);
        setIconImage(new ImageIcon(getClass().getResource("/images/icone.png")).getImage());
        setResizable(false);

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 204));

        txtNomeDesabilitado.setEditable(false);
        txtNomeDesabilitado.setBackground(new java.awt.Color(204, 204, 204));
        txtNomeDesabilitado.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N

        lbNomeDesabilitado.setForeground(new java.awt.Color(255, 255, 255));
        lbNomeDesabilitado.setText("Nome do(a) Funcionário(a)");

        txtMatricula.setEditable(false);
        txtMatricula.setBackground(new java.awt.Color(204, 204, 204));
        txtMatricula.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N

        lbMatricula.setForeground(new java.awt.Color(255, 255, 255));
        lbMatricula.setText("Matrícula");

        jtPainelCadastro.setBackground(new java.awt.Color(204, 204, 204));
        jtPainelCadastro.setPreferredSize(new java.awt.Dimension(914, 300));

        painelDadosDoFuncionario.setBackground(new java.awt.Color(204, 204, 204));
        painelDadosDoFuncionario.setOpaque(false);

        painelDadosPessoaisFuncionario.setBackground(new java.awt.Color(102, 102, 102));
        painelDadosPessoaisFuncionario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pessoal", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        painelDadosPessoaisFuncionario.setOpaque(false);

        lbNomeFuncionario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbNomeFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        lbNomeFuncionario.setLabelFor(txtNomeFuncionario);
        lbNomeFuncionario.setText("Nome Completo (Obrigatório)");

        painelSexo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sexo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        painelSexo.setOpaque(false);

        grupoSexo.add(rbSexoMasculino);
        rbSexoMasculino.setForeground(new java.awt.Color(255, 255, 255));
        rbSexoMasculino.setSelected(true);
        rbSexoMasculino.setText("Masculino");
        rbSexoMasculino.setOpaque(false);

        grupoSexo.add(rbSexoFeminino);
        rbSexoFeminino.setForeground(new java.awt.Color(255, 255, 255));
        rbSexoFeminino.setText("Feminino");
        rbSexoFeminino.setOpaque(false);

        javax.swing.GroupLayout painelSexoLayout = new javax.swing.GroupLayout(painelSexo);
        painelSexo.setLayout(painelSexoLayout);
        painelSexoLayout.setHorizontalGroup(
            painelSexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSexoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbSexoMasculino)
                .addGap(18, 18, 18)
                .addComponent(rbSexoFeminino)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        painelSexoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {rbSexoFeminino, rbSexoMasculino});

        painelSexoLayout.setVerticalGroup(
            painelSexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelSexoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(painelSexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbSexoMasculino)
                    .addComponent(rbSexoFeminino)))
        );

        painelSexoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {rbSexoFeminino, rbSexoMasculino});

        lbDataNascimentoFuncionario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbDataNascimentoFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        lbDataNascimentoFuncionario.setLabelFor(txtDataNascimentoFuncionario);
        lbDataNascimentoFuncionario.setText("Nascimento (Obrigatório)");

        lbNacionalidadeFuncionario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbNacionalidadeFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        lbNacionalidadeFuncionario.setLabelFor(txtNacionalidadeFuncionario);
        lbNacionalidadeFuncionario.setText("Nacionalidade");

        lbNaturalidadeFuncionario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbNaturalidadeFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        lbNaturalidadeFuncionario.setLabelFor(txtNaturalidadeFuncionario);
        lbNaturalidadeFuncionario.setText("Naturalidade");

        jcbUfNaturalidadeFuncionario.setMaximumRowCount(5);
        jcbUfNaturalidadeFuncionario.setModel(new javax.swing.DefaultComboBoxModel<>(Estados.values()));
        jcbUfNaturalidadeFuncionario.setSelectedItem(Estados.PA);
        jcbUfNaturalidadeFuncionario.setOpaque(false);

        lbUfNaturalidadeFuncionario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbUfNaturalidadeFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        lbUfNaturalidadeFuncionario.setLabelFor(jcbUfNaturalidadeFuncionario);
        lbUfNaturalidadeFuncionario.setText("UF");

        try {
            txtDataNascimentoFuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        painelFotoFuncionario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Foto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        painelFotoFuncionario.setOpaque(false);

        lbFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ios7-contact-outline.png"))); // NOI18N
        lbFoto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout painelFotoFuncionarioLayout = new javax.swing.GroupLayout(painelFotoFuncionario);
        painelFotoFuncionario.setLayout(painelFotoFuncionarioLayout);
        painelFotoFuncionarioLayout.setHorizontalGroup(
            painelFotoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        painelFotoFuncionarioLayout.setVerticalGroup(
            painelFotoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lbIdentidadeFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        lbIdentidadeFuncionario.setText("Identidade");

        try {
            txtIdentidadeFuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtCpfFuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-###.##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lbCpfFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        lbCpfFuncionario.setText("Cpf");

        txtDataCadastroFuncionario.setEditable(false);
        txtDataCadastroFuncionario.setText(new SimpleDateFormat("dd/MM/yyyy").format(new Date()));

        lbDataCadastroFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        lbDataCadastroFuncionario.setText("Data Cadastro");

        javax.swing.GroupLayout painelDadosPessoaisFuncionarioLayout = new javax.swing.GroupLayout(painelDadosPessoaisFuncionario);
        painelDadosPessoaisFuncionario.setLayout(painelDadosPessoaisFuncionarioLayout);
        painelDadosPessoaisFuncionarioLayout.setHorizontalGroup(
            painelDadosPessoaisFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosPessoaisFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosPessoaisFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(painelDadosPessoaisFuncionarioLayout.createSequentialGroup()
                        .addGroup(painelDadosPessoaisFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDataNascimentoFuncionario)
                            .addComponent(txtDataNascimentoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelDadosPessoaisFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNacionalidadeFuncionario)
                            .addComponent(txtNacionalidadeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelDadosPessoaisFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNaturalidadeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNaturalidadeFuncionario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelDadosPessoaisFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbUfNaturalidadeFuncionario)
                            .addComponent(jcbUfNaturalidadeFuncionario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(painelDadosPessoaisFuncionarioLayout.createSequentialGroup()
                        .addGroup(painelDadosPessoaisFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNomeFuncionario)
                            .addComponent(txtNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painelSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelDadosPessoaisFuncionarioLayout.createSequentialGroup()
                        .addGroup(painelDadosPessoaisFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelDadosPessoaisFuncionarioLayout.createSequentialGroup()
                                .addComponent(txtIdentidadeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCpfFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelDadosPessoaisFuncionarioLayout.createSequentialGroup()
                                .addComponent(lbIdentidadeFuncionario)
                                .addGap(178, 178, 178)
                                .addComponent(lbCpfFuncionario)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelDadosPessoaisFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDataCadastroFuncionario)
                            .addComponent(txtDataCadastroFuncionario))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(painelFotoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        painelDadosPessoaisFuncionarioLayout.setVerticalGroup(
            painelDadosPessoaisFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosPessoaisFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosPessoaisFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDadosPessoaisFuncionarioLayout.createSequentialGroup()
                        .addGroup(painelDadosPessoaisFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(painelSexo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(painelDadosPessoaisFuncionarioLayout.createSequentialGroup()
                                .addComponent(lbNomeFuncionario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelDadosPessoaisFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelDadosPessoaisFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbNacionalidadeFuncionario)
                                .addComponent(lbNaturalidadeFuncionario)
                                .addComponent(lbUfNaturalidadeFuncionario))
                            .addComponent(lbDataNascimentoFuncionario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelDadosPessoaisFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNacionalidadeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNaturalidadeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbUfNaturalidadeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDataNascimentoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(painelDadosPessoaisFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbIdentidadeFuncionario)
                            .addComponent(lbCpfFuncionario)
                            .addComponent(lbDataCadastroFuncionario)))
                    .addComponent(painelFotoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosPessoaisFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdentidadeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCpfFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataCadastroFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        painelEnderecoFuncionario.setBackground(new java.awt.Color(102, 102, 102));
        painelEnderecoFuncionario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Residencial", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        painelEnderecoFuncionario.setOpaque(false);

        lbEnderecoFuncionario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbEnderecoFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        lbEnderecoFuncionario.setLabelFor(txtEnderecoFuncionario);
        lbEnderecoFuncionario.setText("Endereço");

        lbComplementoEnderecoFuncionario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbComplementoEnderecoFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        lbComplementoEnderecoFuncionario.setLabelFor(txtComplementoEnderecoFuncionario);
        lbComplementoEnderecoFuncionario.setText("Complemento do Endereço");

        lbCidadeFuncionario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbCidadeFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        lbCidadeFuncionario.setText("Cidade");

        jcbUfResidenciaFuncionario.setMaximumRowCount(5);
        jcbUfResidenciaFuncionario.setModel(new javax.swing.DefaultComboBoxModel<>(Estados.values()));
        jcbUfResidenciaFuncionario.setSelectedItem(Estados.PA);

        lbUfResidenciaFuncionario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbUfResidenciaFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        lbUfResidenciaFuncionario.setText("UF");

        try {
            txtCepFuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtTelefoneFuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lbCepFuncionario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbCepFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        lbCepFuncionario.setText("CEP");

        lbTelefoneFuncionario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbTelefoneFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        lbTelefoneFuncionario.setText("Telefone");

        lbCelularFuncionario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbCelularFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        lbCelularFuncionario.setText("Celular");

        lbEmailFuncionario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbEmailFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        lbEmailFuncionario.setText("Email");

        try {
            txtCelularFuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lbBairroFuncionario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbBairroFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        lbBairroFuncionario.setLabelFor(txtBairroFuncionario);
        lbBairroFuncionario.setText("Bairro");

        javax.swing.GroupLayout painelEnderecoFuncionarioLayout = new javax.swing.GroupLayout(painelEnderecoFuncionario);
        painelEnderecoFuncionario.setLayout(painelEnderecoFuncionarioLayout);
        painelEnderecoFuncionarioLayout.setHorizontalGroup(
            painelEnderecoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEnderecoFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelEnderecoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelEnderecoFuncionarioLayout.createSequentialGroup()
                        .addGroup(painelEnderecoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCidadeFuncionario)
                            .addComponent(txtCidadeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelEnderecoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbUfResidenciaFuncionario)
                            .addComponent(jcbUfResidenciaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelEnderecoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCepFuncionario)
                            .addComponent(txtCepFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelEnderecoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelefoneFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTelefoneFuncionario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelEnderecoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCelularFuncionario)
                            .addComponent(txtCelularFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelEnderecoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmailFuncionario)
                            .addGroup(painelEnderecoFuncionarioLayout.createSequentialGroup()
                                .addComponent(lbEmailFuncionario)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(painelEnderecoFuncionarioLayout.createSequentialGroup()
                        .addGroup(painelEnderecoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbEnderecoFuncionario)
                            .addComponent(txtEnderecoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelEnderecoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtComplementoEnderecoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbComplementoEnderecoFuncionario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelEnderecoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelEnderecoFuncionarioLayout.createSequentialGroup()
                                .addComponent(lbBairroFuncionario)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtBairroFuncionario))))
                .addContainerGap())
        );

        painelEnderecoFuncionarioLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtCelularFuncionario, txtTelefoneFuncionario});

        painelEnderecoFuncionarioLayout.setVerticalGroup(
            painelEnderecoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEnderecoFuncionarioLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(painelEnderecoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEnderecoFuncionario)
                    .addComponent(lbComplementoEnderecoFuncionario)
                    .addComponent(lbBairroFuncionario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelEnderecoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEnderecoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtComplementoEnderecoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBairroFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelEnderecoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCidadeFuncionario)
                    .addComponent(lbUfResidenciaFuncionario)
                    .addComponent(lbCepFuncionario)
                    .addComponent(lbTelefoneFuncionario)
                    .addComponent(lbCelularFuncionario)
                    .addComponent(lbEmailFuncionario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelEnderecoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCidadeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbUfResidenciaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCepFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefoneFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCelularFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelDadosDoFuncionarioLayout = new javax.swing.GroupLayout(painelDadosDoFuncionario);
        painelDadosDoFuncionario.setLayout(painelDadosDoFuncionarioLayout);
        painelDadosDoFuncionarioLayout.setHorizontalGroup(
            painelDadosDoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosDoFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosDoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelEnderecoFuncionario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelDadosPessoaisFuncionario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        painelDadosDoFuncionarioLayout.setVerticalGroup(
            painelDadosDoFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosDoFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelDadosPessoaisFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelEnderecoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jtPainelCadastro.addTab("Informações do(a) Funcionário(a)", painelDadosDoFuncionario);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setOpaque(false);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Função", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setOpaque(false);

        jcbCargoFuncao.setMaximumRowCount(5);
        jcbCargoFuncao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cargo/Função" }));

        lbTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lbTitulo.setText("Cargo/Função (Obrigatório)");

        lbCurso.setForeground(new java.awt.Color(255, 255, 255));
        lbCurso.setText("Carga Horária (Obrigatório)");

        lbInstituicao.setForeground(new java.awt.Color(255, 255, 255));
        lbInstituicao.setText("Escolaridade (Obrigatório)");

        jcbEscolaridade.setMaximumRowCount(5);
        jcbEscolaridade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Ensino Fundamental Incompleto", "Ensino Fundamental Completo", "Ensino Médio Incompleto", "Ensino Médio Completo", "Nível Superior Incompleto", "Níevel Superiro Completo" }));

        txtCargaHoraria.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCargaHoraria.setText("44");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbCargoFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTitulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCurso)
                    .addComponent(txtCargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbInstituicao)
                        .addGap(0, 262, Short.MAX_VALUE))
                    .addComponent(jcbEscolaridade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTitulo)
                    .addComponent(lbCurso)
                    .addComponent(lbInstituicao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbCargoFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbEscolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descrição da Função", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setOpaque(false);

        txtDescricaoFuncao.setEditable(false);
        jScrollPane1.setViewportView(txtDescricaoFuncao);

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastrar como Usuário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel5.setOpaque(false);

        grupoUsuario.add(rbUsuarioSim);
        rbUsuarioSim.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbUsuarioSim.setForeground(new java.awt.Color(255, 255, 255));
        rbUsuarioSim.setText("Sim");
        rbUsuarioSim.setOpaque(false);

        grupoUsuario.add(rbUsuarioNao);
        rbUsuarioNao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbUsuarioNao.setForeground(new java.awt.Color(255, 255, 255));
        rbUsuarioNao.setSelected(true);
        rbUsuarioNao.setText("Não");
        rbUsuarioNao.setOpaque(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(rbUsuarioSim)
                .addGap(30, 30, 30)
                .addComponent(rbUsuarioNao)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbUsuarioSim)
                    .addComponent(rbUsuarioNao))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Carteira de Trabalho", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel4.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Número (Obrigatório)");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Série (Obrigatório)");

        try {
            txtDataEmissao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Data Emissão (Obrigatório)");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Número do PIS");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Dependentes");

        txtDependentes.setText("0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumeroCTPS, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSerieCTPS, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumeroPIS, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtDependentes))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 165, Short.MAX_VALUE))
                    .addComponent(txtDataEmissao))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroCTPS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSerieCTPS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroPIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDependentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jtPainelCadastro.addTab("Informações da Função", jPanel1);

        jPanel6.setOpaque(false);

        jPanel7.setBackground(new java.awt.Color(102, 102, 102));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Confirmar Informações", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel7.setOpaque(false);

        txtConfirmar.setEditable(false);
        txtConfirmar.setBackground(new java.awt.Color(204, 204, 204));
        txtConfirmar.setBorder(null);
        txtConfirmar.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        txtConfirmar.setOpaque(false);
        jScrollPane2.setViewportView(txtConfirmar);

        jPanel8.setBackground(new java.awt.Color(102, 102, 102));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Comandos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel8.setOpaque(false);

        btnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/checkmark-round.png"))); // NOI18N
        btnConfirmar.setText("CONFIRMAR");
        btnConfirmar.setIconTextGap(10);

        btnCorrigir.setText("CORRIGIR");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCorrigir, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                    .addComponent(btnConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCorrigir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtPainelCadastro.addTab("Confirmar Cadastro", jPanel6);

        btnProximoPasso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrow-right-c.png"))); // NOI18N
        btnProximoPasso.setText("Próximo Passo");
        btnProximoPasso.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnProximoPasso.setIconTextGap(20);

        btnCancelar.setText("Cancelar");

        jDesktopPane1.setLayer(txtNomeDesabilitado, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lbNomeDesabilitado, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtMatricula, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lbMatricula, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jtPainelCadastro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnProximoPasso, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnCancelar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtPainelCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(lbMatricula)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbNomeDesabilitado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNomeDesabilitado, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(btnProximoPasso, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeDesabilitado, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNomeDesabilitado)
                    .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMatricula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtPainelCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProximoPasso, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * 
     * @param usuario dados do usuario
     */
    public void editarFuncionario(Usuario usuario) {
        this.lbFoto.setName(usuario.getFoto());
        this.lbFoto.setIcon(new ImageIcon(Arquivo.DIR_FOTOS.concat(usuario.getFoto())));

        this.txtNomeDesabilitado.setText(usuario.getNome());
        this.txtMatricula.setText(usuario.getMatricula());
        
        this.txtNomeFuncionario.setText(usuario.getNome());
        this.rbSexoMasculino.setSelected(usuario.getSexo().equals("Masculino"));
        this.rbSexoFeminino.setSelected(usuario.getSexo().equals("Feminino"));
        this.txtDataNascimentoFuncionario.setText(usuario.getDataNascimento());
        this.txtNacionalidadeFuncionario.setText(usuario.getNacionalidade());
        this.txtNaturalidadeFuncionario.setText(usuario.getNaturalidade());
        this.jcbUfNaturalidadeFuncionario.setSelectedItem(usuario.getUfNaturalidade());
        this.txtIdentidadeFuncionario.setText(usuario.getIdentidade());
        this.txtCpfFuncionario.setText(usuario.getCpf());
        this.txtDataCadastroFuncionario.setText(usuario.getDataCadastro());
        this.txtEnderecoFuncionario.setText(usuario.getEndereco());
        this.txtComplementoEnderecoFuncionario.setText(usuario.getComplemento());
        this.txtBairroFuncionario.setText(usuario.getBairro());
        this.txtCidadeFuncionario.setText(usuario.getCidade());
        this.jcbUfResidenciaFuncionario.setSelectedItem(usuario.getUfNaturalidade());
        this.txtCepFuncionario.setText(usuario.getCep());
        this.txtCpfFuncionario.setText(usuario.getCpf());
        this.txtTelefoneFuncionario.setText(usuario.getTelefone());
        this.txtCelularFuncionario.setText(usuario.getCelular());
        this.txtEmailFuncionario.setText(usuario.getEmail());

        this.txtCargaHoraria.setText(String.valueOf(usuario.getCargaHoraria()));

        this.jcbCargoFuncao.setSelectedItem(usuario.getCargoFuncao());
        this.jcbEscolaridade.setSelectedItem(usuario.getEscolaridade());
        this.txtNumeroCTPS.setText(usuario.getNumeroCtps());
        this.txtSerieCTPS.setText(usuario.getSerieCtps());
        this.txtDataEmissao.setText(usuario.getDataEmissaoCarteira());
        this.txtNumeroPIS.setText(usuario.getNumeroPis());
        this.txtDependentes.setText(String.valueOf(usuario.getDependentes()));

        this.rbUsuarioSim.setSelected(usuario.isUsuario());
        
        if (usuario.isUsuario()) {
            this.telaCadastroUsuario.getTxtLogin().setText(usuario.getUsuario());
            this.telaCadastroUsuario.getTxtSenha().setText(usuario.getSenha());
            this.telaCadastroUsuario.getTxtRepetirSenha().setText(usuario.getSenha());
            this.telaCadastroUsuario.getCheckUsuarioMaster().setSelected(usuario.isUsuarioMaster());

            this.telaCadastroUsuario.getRbCAAlunoSim().setSelected(usuario.isCadastrarAtualizarAluno());
            this.telaCadastroUsuario.getRbCAProfessorSim().setSelected(usuario.isCadastrarAtualizarProfessor());
            this.telaCadastroUsuario.getRbCAFuncionarioSim().setSelected(usuario.isCadastrarAtualizarFuncionario());
            this.telaCadastroUsuario.getRbCadastrarUsuarioSim().setSelected(usuario.isCadastrarUsuario());
            this.telaCadastroUsuario.getRbControleFinanceiroSim().setSelected(usuario.isControleFinanceiro());
            this.telaCadastroUsuario.getRbExcluirAlunoSim().setSelected(usuario.isExcluirAluno());
            this.telaCadastroUsuario.getRbExcluirProfessorSim().setSelected(usuario.isExcluirProfessor());
            this.telaCadastroUsuario.getRbExcluirFuncionarioSim().setSelected(usuario.isExcluirFuncionario());
            this.telaCadastroUsuario.getRbExcluirUsuarioSim().setSelected(usuario.isExcluirUsuario());
            this.telaCadastroUsuario.getRbEmitirRelatoriosSim().setSelected(usuario.isEmitirRelatorios());
            this.telaCadastroUsuario.getRbCATurmaSim().setSelected(usuario.isCadastrarAlterarTurma());
            this.telaCadastroUsuario.getRbCADisciplinaSim().setSelected(usuario.isCadastrarAlterarDisciplina());
            this.telaCadastroUsuario.getRbExcluirTurmaSim().setSelected(usuario.isExcluirTurma());
            this.telaCadastroUsuario.getRbExcluirDisciplinaSim().setSelected(usuario.isExcluirDisciplina());
            this.telaCadastroUsuario.getRbEmitirDocumentosSim().setSelected(usuario.isEmitirDocumentos());
            this.telaCadastroUsuario.getRbCAFornecedorSim().setSelected(usuario.isCadastrarAtualizarFornecedores());
            this.telaCadastroUsuario.getRbCABensConsumorSim().setSelected(usuario.isCadastrarAtualizarBensPatrimoniais());
            this.telaCadastroUsuario.getRbExcluirFornecedoresSim().setSelected(usuario.isExcluirFornecedores());
            this.telaCadastroUsuario.getRbExcluirBensConsumoSim().setSelected(usuario.isExcluirBensPatrimoniais());
            
            this.jtPainelCadastro.setSelectedIndex(0);
        }
    }
    
    public TelaCadastroUsuario getTelaCadastroUsuario() {
        return telaCadastroUsuario;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public JButton getBtnConfirmar() {
        return btnConfirmar;
    }

    public JButton getBtnCorrigir() {
        return btnCorrigir;
    }

    public JButton getBtnProximoPasso() {
        return btnProximoPasso;
    }

    public JComboBox<String> getJcbCargoFuncao() {
        return jcbCargoFuncao;
    }

    public JComboBox<String> getJcbEscolaridade() {
        return jcbEscolaridade;
    }

    public JComboBox<Estados> getJcbUfNaturalidadeFuncionario() {
        return jcbUfNaturalidadeFuncionario;
    }

    public JComboBox<Estados> getJcbUfResidenciaFuncionario() {
        return jcbUfResidenciaFuncionario;
    }

    public JRadioButton getRbSexoFeminino() {
        return rbSexoFeminino;
    }

    public JRadioButton getRbSexoMasculino() {
        return rbSexoMasculino;
    }

    public JRadioButton getRbUsuarioNao() {
        return rbUsuarioNao;
    }

    public JRadioButton getRbUsuarioSim() {
        return rbUsuarioSim;
    }

    public JTextField getTxtBairroFuncionario() {
        return txtBairroFuncionario;
    }

    public JTextField getTxtCargaHoraria() {
        return txtCargaHoraria;
    }

    public JFormattedTextField getTxtCelularFuncionario() {
        return txtCelularFuncionario;
    }

    public JFormattedTextField getTxtCepFuncionario() {
        return txtCepFuncionario;
    }

    public JTextField getTxtCidadeFuncionario() {
        return txtCidadeFuncionario;
    }

    public JTextField getTxtComplementoEnderecoFuncionario() {
        return txtComplementoEnderecoFuncionario;
    }

    public JTextPane getTxtConfirmar() {
        return txtConfirmar;
    }

    public JFormattedTextField getTxtCpfFuncionario() {
        return txtCpfFuncionario;
    }

    public JTextField getTxtDataCadastroFuncionario() {
        return txtDataCadastroFuncionario;
    }

    public JFormattedTextField getTxtDataEmissao() {
        return txtDataEmissao;
    }

    public JFormattedTextField getTxtDataNascimentoFuncionario() {
        return txtDataNascimentoFuncionario;
    }

    public JTextField getTxtDependentes() {
        return txtDependentes;
    }

    public JTextPane getTxtDescricaoFuncao() {
        return txtDescricaoFuncao;
    }

    public JTextField getTxtEmailFuncionario() {
        return txtEmailFuncionario;
    }

    public JTextField getTxtEnderecoFuncionario() {
        return txtEnderecoFuncionario;
    }

    public JFormattedTextField getTxtIdentidadeFuncionario() {
        return txtIdentidadeFuncionario;
    }

    public JTextField getTxtMatricula() {
        return txtMatricula;
    }

    public JTextField getTxtNacionalidadeFuncionario() {
        return txtNacionalidadeFuncionario;
    }

    public JTextField getTxtNaturalidadeFuncionario() {
        return txtNaturalidadeFuncionario;
    }

    public JTextField getTxtNomeDesabilitado() {
        return txtNomeDesabilitado;
    }

    public JTextField getTxtNomeFuncionario() {
        return txtNomeFuncionario;
    }

    public JTextField getTxtNumeroCTPS() {
        return txtNumeroCTPS;
    }

    public JTextField getTxtNumeroPIS() {
        return txtNumeroPIS;
    }

    public JTextField getTxtSerieCTPS() {
        return txtSerieCTPS;
    }

    public JFormattedTextField getTxtTelefoneFuncionario() {
        return txtTelefoneFuncionario;
    }

    public JLabel getLbFoto() {
        return lbFoto;
    }

    public JTabbedPane getJtPainelCadastro() {
        return jtPainelCadastro;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnCorrigir;
    private javax.swing.JButton btnProximoPasso;
    private javax.swing.ButtonGroup grupoSexo;
    private javax.swing.ButtonGroup grupoUsuario;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jcbCargoFuncao;
    private javax.swing.JComboBox<String> jcbEscolaridade;
    private javax.swing.JComboBox<Estados> jcbUfNaturalidadeFuncionario;
    private javax.swing.JComboBox<Estados> jcbUfResidenciaFuncionario;
    private javax.swing.JTabbedPane jtPainelCadastro;
    private javax.swing.JLabel lbBairroFuncionario;
    private javax.swing.JLabel lbCelularFuncionario;
    private javax.swing.JLabel lbCepFuncionario;
    private javax.swing.JLabel lbCidadeFuncionario;
    private javax.swing.JLabel lbComplementoEnderecoFuncionario;
    private javax.swing.JLabel lbCpfFuncionario;
    private javax.swing.JLabel lbCurso;
    private javax.swing.JLabel lbDataCadastroFuncionario;
    private javax.swing.JLabel lbDataNascimentoFuncionario;
    private javax.swing.JLabel lbEmailFuncionario;
    private javax.swing.JLabel lbEnderecoFuncionario;
    private javax.swing.JLabel lbFoto;
    private javax.swing.JLabel lbIdentidadeFuncionario;
    private javax.swing.JLabel lbInstituicao;
    private javax.swing.JLabel lbMatricula;
    private javax.swing.JLabel lbNacionalidadeFuncionario;
    private javax.swing.JLabel lbNaturalidadeFuncionario;
    private javax.swing.JLabel lbNomeDesabilitado;
    private javax.swing.JLabel lbNomeFuncionario;
    private javax.swing.JLabel lbTelefoneFuncionario;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbUfNaturalidadeFuncionario;
    private javax.swing.JLabel lbUfResidenciaFuncionario;
    private javax.swing.JPanel painelDadosDoFuncionario;
    private javax.swing.JPanel painelDadosPessoaisFuncionario;
    private javax.swing.JPanel painelEnderecoFuncionario;
    private javax.swing.JPanel painelFotoFuncionario;
    private javax.swing.JPanel painelSexo;
    private javax.swing.JRadioButton rbSexoFeminino;
    private javax.swing.JRadioButton rbSexoMasculino;
    private javax.swing.JRadioButton rbUsuarioNao;
    private javax.swing.JRadioButton rbUsuarioSim;
    private javax.swing.JTextField txtBairroFuncionario;
    private javax.swing.JTextField txtCargaHoraria;
    private javax.swing.JFormattedTextField txtCelularFuncionario;
    private javax.swing.JFormattedTextField txtCepFuncionario;
    private javax.swing.JTextField txtCidadeFuncionario;
    private javax.swing.JTextField txtComplementoEnderecoFuncionario;
    private javax.swing.JTextPane txtConfirmar;
    private javax.swing.JFormattedTextField txtCpfFuncionario;
    private javax.swing.JTextField txtDataCadastroFuncionario;
    private javax.swing.JFormattedTextField txtDataEmissao;
    private javax.swing.JFormattedTextField txtDataNascimentoFuncionario;
    private javax.swing.JTextField txtDependentes;
    private javax.swing.JTextPane txtDescricaoFuncao;
    private javax.swing.JTextField txtEmailFuncionario;
    private javax.swing.JTextField txtEnderecoFuncionario;
    private javax.swing.JFormattedTextField txtIdentidadeFuncionario;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNacionalidadeFuncionario;
    private javax.swing.JTextField txtNaturalidadeFuncionario;
    private javax.swing.JTextField txtNomeDesabilitado;
    private javax.swing.JTextField txtNomeFuncionario;
    private javax.swing.JTextField txtNumeroCTPS;
    private javax.swing.JTextField txtNumeroPIS;
    private javax.swing.JTextField txtSerieCTPS;
    private javax.swing.JFormattedTextField txtTelefoneFuncionario;
    // End of variables declaration//GEN-END:variables

    private final int returnStatus = RET_CANCEL;
}
